import 'package:flutter/foundation.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

import '../config/app_config.dart';

/// Where a [GeminiProxyResult] came from.
enum GeminiProxySource {
  /// Shared prompt-hash cache hit inside the edge function (T2, $0).
  cache,

  /// Freshly generated by Gemini through the proxy (T3).
  live,

  /// The edge function was reachable but reported a server error.
  error,

  /// No Supabase backend is configured, or the request never reached the
  /// network (offline / function unreachable).
  offline,

  /// The server rejected the request because the per-user hourly limit of
  /// live AI calls was exhausted.
  rateLimited,
}

/// Result of a request to the `gemini-proxy` edge function.
class GeminiProxyResult {
  const GeminiProxyResult(this.text, this.source);

  /// Empty for [GeminiProxySource.offline] / [GeminiProxySource.rateLimited].
  final String text;
  final GeminiProxySource source;

  bool get isFromCache => source == GeminiProxySource.cache;
  bool get isOffline => source == GeminiProxySource.offline;
  bool get isRateLimited => source == GeminiProxySource.rateLimited;
}

/// Invokes a Supabase edge function and returns its decoded JSON `data`.
typedef GeminiInvoker = Future<dynamic> Function(String name, {Object? body});

Future<dynamic> _defaultInvoker(String name, {Object? body}) async {
  final res = await Supabase.instance.client.functions.invoke(name, body: body);
  return res.data;
}

/// Client for the `gemini-proxy` Supabase Edge Function.
///
/// Implements the app's T2/T3 AI tiers:
///   T2 — the function serves shared cached answers (cache source, $0).
///   T3 — the function calls Gemini and write-through caches the result.
///
/// The local T1 tier (questions.explanation already in Drift) is resolved by
/// the caller, which owns the database handle.
class GeminiProxyService {
  GeminiProxyService({GeminiInvoker? invoker, bool? configured})
      : _invoker = invoker ?? _defaultInvoker,
        _configured = configured;

  final GeminiInvoker _invoker;
  final bool? _configured;

  /// Whether a Supabase backend is wired up via --dart-define.
  bool get isConfigured => _configured ?? AppConfig.isCloudAuthConfigured;

  /// Sends [prompt] to the proxy. Never throws — errors are mapped onto
  /// [GeminiProxyResult.source] so callers can pick a graceful fallback.
  Future<GeminiProxyResult> generate({
    required String prompt,
    String? systemPrompt,
    String? questionId,
  }) async {
    if (!isConfigured) {
      return const GeminiProxyResult('', GeminiProxySource.offline);
    }

    try {
      final data = await _invoker(
        'gemini-proxy',
        body: {
          'prompt': prompt,
          if (systemPrompt != null && systemPrompt.isNotEmpty)
            'systemPrompt': systemPrompt,
          if (questionId != null && questionId.isNotEmpty)
            'questionId': questionId,
        },
      );

      if (data is! Map) {
        return const GeminiProxyResult(
          'AI service returned an unexpected response.',
          GeminiProxySource.error,
        );
      }

      final text = data['response'];
      final source = data['source'];
      if (text is! String || text.trim().isEmpty) {
        return const GeminiProxyResult(
          'AI service returned an empty response.',
          GeminiProxySource.error,
        );
      }

      if (source == 'cache') {
        return GeminiProxyResult(text.trim(), GeminiProxySource.cache);
      }
      return GeminiProxyResult(text.trim(), GeminiProxySource.live);
    } on FunctionException catch (e) {
      if (e.status == 429) {
        return const GeminiProxyResult('', GeminiProxySource.rateLimited);
      }
      return GeminiProxyResult(
        'AI service error (HTTP ${e.status}).',
        GeminiProxySource.error,
      );
    } catch (e) {
      debugPrint('❌ gemini-proxy unreachable: $e');
      return const GeminiProxyResult('', GeminiProxySource.offline);
    }
  }
}
