import 'package:flutter/foundation.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

import '../config/app_config.dart';
import '../models/chat_context.dart';

/// Where a [GeminiProxyResult] came from.
enum GeminiProxySource {
  /// Shared prompt-hash cache hit inside the edge function (T2, $0).
  cache,

  /// Freshly generated by Gemini through the proxy (T3).
  live,

  /// The edge function was reachable but reported a server error.
  error,

  /// No Supabase backend is configured, or the request never reached the
  /// network (offline / function unreachable).
  offline,

  /// The server rejected the request because the per-user hourly limit of
  /// live AI calls was exhausted.
  rateLimited,
}

/// Result of a request to the `gemini-proxy` edge function.
class GeminiProxyResult {
  const GeminiProxyResult(this.text, this.source);

  /// Empty for [GeminiProxySource.offline] / [GeminiProxySource.rateLimited].
  final String text;
  final GeminiProxySource source;

  bool get isFromCache => source == GeminiProxySource.cache;
  bool get isOffline => source == GeminiProxySource.offline;
  bool get isRateLimited => source == GeminiProxySource.rateLimited;
}

/// Invokes a Supabase edge function and returns its decoded JSON `data`.
typedef GeminiInvoker = Future<dynamic> Function(String name, {Object? body});

Future<dynamic> _defaultInvoker(String name, {Object? body}) async {
  if (!AppConfig.enableAiProxy) {
    throw Exception('AI proxy is disabled');
  }
  try {
    final res = await Supabase.instance.client.functions.invoke(name, body: body);
    return res.data;
  } on Exception catch (e) {
    debugPrint('Supabase not initialized or function failed: $e');
    rethrow;
  }
}


/// Client for the `gemini-proxy` Supabase Edge Function.
///
/// Implements the app's T2/T3 AI tiers:
///   T2 — the function serves shared cached answers (cache source, $0).
///   T3 — the function calls Gemini and write-through caches the result.
///
/// The local T1 tier (questions.explanation already in Drift) is resolved by
/// the caller, which owns the database handle.
class GeminiProxyService {
  GeminiProxyService({GeminiInvoker? invoker, bool? configured})
      : _invoker = invoker ?? _defaultInvoker,
        _configured = configured;

  final GeminiInvoker _invoker;
  final bool? _configured;

  bool get isConfigured => _configured ?? (AppConfig.enableAiProxy && AppConfig.isCloudAuthConfigured);

  /// Build a context-aware system prompt for the AI tutor.
  String _buildSystemPrompt(ChatContext context) {
    final buffer = StringBuffer();
    buffer.write('You are an expert NEET tutor for a ${context.userBatch} student. ');
    buffer.write('They are currently studying ${context.currentChapter}. ');

    if (context.weakTopics.isNotEmpty) {
      buffer.write('Their weak topics are: ${context.weakTopics.join(', ')}. ');
      buffer.write('Prioritize explaining these with extra examples and memory tricks. ');
    }

    buffer.write('They have ${context.daysToExam} days until NEET 2026. ');
    buffer.write('Accuracy: ${(context.accuracy * 100).toInt()}% (${context.questionsSolved} questions solved). ');

    if (context.studyMode == StudyMode.coachingStudent) {
      buffer.write('Assume they have coaching notes — reference NCERT first, then coaching material. ');
    } else {
      buffer.write('They are self-studying — make explanations self-contained with NCERT references. ');
    }

    buffer.write('Use simple Hindi-English mix if the question is in Hinglish. ');
    buffer.write('For Biology: use mnemonics and diagrams descriptions. ');
    buffer.write('For Physics: show step-by-step formulas with units. ');
    buffer.write('For Chemistry: show reaction mechanisms for organic, periodic trends for inorganic. ');

    return buffer.toString();
  }

  /// Sends [prompt] to the proxy. Never throws — errors are mapped onto
  /// [GeminiProxyResult.source] so callers can pick a graceful fallback.
  Future<GeminiProxyResult> generate({
    required String prompt,
    ChatContext? context,
    String? questionId,
    String? systemPrompt,
  }) async {
    if (!isConfigured) {
      return const GeminiProxyResult('', GeminiProxySource.offline);
    }

    // Build context-aware system prompt if context is provided
    String? finalSystemPrompt = systemPrompt;
    if (finalSystemPrompt == null && context != null) {
      finalSystemPrompt = _buildSystemPrompt(context);
    }

    try {
      final data = await _invoker(
        'gemini-proxy',
        body: {
          'prompt': prompt,
          if (finalSystemPrompt != null && finalSystemPrompt.isNotEmpty)
            'systemPrompt': finalSystemPrompt,
          if (questionId != null && questionId.isNotEmpty)
            'questionId': questionId,
        },
      );

      if (data is! Map) {
        return const GeminiProxyResult(
          'AI service returned an unexpected response.',
          GeminiProxySource.error,
        );
      }

      final text = data['response'];
      final source = data['source'];
      if (text is! String || text.trim().isEmpty) {
        return const GeminiProxyResult(
          'AI service returned an empty response.',
          GeminiProxySource.error,
        );
      }

      if (source == 'cache') {
        return GeminiProxyResult(text.trim(), GeminiProxySource.cache);
      }
      return GeminiProxyResult(text.trim(), GeminiProxySource.live);
    } on FunctionException catch (e) {
      if (e.status == 429) {
        return const GeminiProxyResult('', GeminiProxySource.rateLimited);
      }
      return GeminiProxyResult(
        'AI service error (HTTP ${e.status}).',
        GeminiProxySource.error,
      );
    } catch (e) {
      debugPrint('❌ gemini-proxy unreachable: $e');
      return const GeminiProxyResult('', GeminiProxySource.offline);
    }
  }
}
