import '../models/question_model.dart';
import '../models/subject_model.dart';

// ============= BIOLOGY: FULL SYLLABUS & QUESTIONS =============

final List<Subject> neetSubjectsPhase2 = [
  Subject(
    id: 'bio',
    name: 'Biology',
    icon: '🧬',
    chapters: [
      Chapter(
        id: 'bio_ch1',
        name: 'The Living World',
        subjectId: 'bio',
        description: 'Introduction to living organisms and taxonomy',
        classLevel: 'Class 11',
        weight: 1,
        topics: [
          Topic(
            id: 'bio_ch1_t1',
            name: 'Characteristics of Living Organisms',
            chapterId: 'bio_ch1',
            description: 'Key features that define life',
            weight: 1,
            questionCount: 4,
            difficulty: 'Easy',
          ),
          Topic(
            id: 'bio_ch1_t2',
            name: 'Diversity in Living Organisms',
            chapterId: 'bio_ch1',
            description: 'Classification and diversity of life',
            weight: 2,
            questionCount: 3,
            difficulty: 'Medium',
          ),
        ],
      ),
      Chapter(
        id: 'bio_ch2',
        name: 'Biological Classification',
        subjectId: 'bio',
        description: 'Five kingdom classification system',
        classLevel: 'Class 11',
        weight: 2,
        topics: [
          Topic(
            id: 'bio_ch2_t1',
            name: 'Monera & Protista',
            chapterId: 'bio_ch2',
            weight: 1,
            questionCount: 3,
            difficulty: 'Medium',
          ),
          Topic(
            id: 'bio_ch2_t2',
            name: 'Fungi, Plantae, Animalia',
            chapterId: 'bio_ch2',
            weight: 1,
            questionCount: 2,
            difficulty: 'Medium',
          ),
        ],
      ),
      Chapter(
        id: 'bio_ch3',
        name: 'Cell: The Unit of Life',
        subjectId: 'bio',
        description: 'Cell structure and functions',
        classLevel: 'Class 11',
        weight: 3,
        topics: [
          Topic(
            id: 'bio_ch3_t1',
            name: 'Prokaryotic & Eukaryotic Cells',
            chapterId: 'bio_ch3',
            weight: 2,
            questionCount: 5,
            difficulty: 'Medium',
          ),
          Topic(
            id: 'bio_ch3_t2',
            name: 'Cell Organelles',
            chapterId: 'bio_ch3',
            weight: 2,
            questionCount: 4,
            difficulty: 'Hard',
          ),
        ],
      ),
      Chapter(
        id: 'bio_ch4',
        name: 'Biomolecules',
        subjectId: 'bio',
        description: 'Carbohydrates, lipids, proteins, nucleic acids',
        classLevel: 'Class 11',
        weight: 2,
        topics: [
          Topic(
            id: 'bio_ch4_t1',
            name: 'Carbohydrates & Lipids',
            chapterId: 'bio_ch4',
            weight: 1,
            questionCount: 3,
            difficulty: 'Easy',
          ),
          Topic(
            id: 'bio_ch4_t2',
            name: 'Proteins & Nucleic Acids',
            chapterId: 'bio_ch4',
            weight: 2,
            questionCount: 4,
            difficulty: 'Hard',
          ),
        ],
      ),
      Chapter(
        id: 'bio_ch5',
        name: 'Cell Division',
        subjectId: 'bio',
        description: 'Mitosis, meiosis, and cell cycle',
        classLevel: 'Class 11',
        weight: 3,
        topics: [
          Topic(
            id: 'bio_ch5_t1',
            name: 'Cell Cycle & Mitosis',
            chapterId: 'bio_ch5',
            weight: 2,
            questionCount: 4,
            difficulty: 'Medium',
          ),
          Topic(
            id: 'bio_ch5_t2',
            name: 'Meiosis',
            chapterId: 'bio_ch5',
            weight: 2,
            questionCount: 3,
            difficulty: 'Hard',
          ),
        ],
      ),
    ],
  ),
  Subject(
    id: 'chem',
    name: 'Chemistry',
    icon: '⚗️',
    chapters: [
      Chapter(
        id: 'chem_ch1',
        name: 'Some Basic Concepts of Chemistry',
        subjectId: 'chem',
        description: 'Mole concept and stoichiometry',
        classLevel: 'Class 11',
        weight: 2,
        topics: [
          Topic(
            id: 'chem_ch1_t1',
            name: 'Mole Concept & Calculations',
            chapterId: 'chem_ch1',
            weight: 3,
            questionCount: 5,
            difficulty: 'Medium',
          ),
          Topic(
            id: 'chem_ch1_t2',
            name: 'Stoichiometry',
            chapterId: 'chem_ch1',
            weight: 2,
            questionCount: 3,
            difficulty: 'Medium',
          ),
        ],
      ),
      Chapter(
        id: 'chem_ch2',
        name: 'Structure of Atom',
        subjectId: 'chem',
        description: 'Atomic models and quantum numbers',
        classLevel: 'Class 11',
        weight: 2,
        topics: [
          Topic(
            id: 'chem_ch2_t1',
            name: 'Bohr & Quantum Models',
            chapterId: 'chem_ch2',
            weight: 2,
            questionCount: 4,
            difficulty: 'Hard',
          ),
          Topic(
            id: 'chem_ch2_t2',
            name: 'Quantum Numbers & Orbitals',
            chapterId: 'chem_ch2',
            weight: 2,
            questionCount: 3,
            difficulty: 'Hard',
          ),
        ],
      ),
      Chapter(
        id: 'chem_ch3',
        name: 'Classification of Elements',
        subjectId: 'chem',
        description: 'Periodic table and properties',
        classLevel: 'Class 11',
        weight: 2,
        topics: [
          Topic(
            id: 'chem_ch3_t1',
            name: 'Periodic Table & Periodicity',
            chapterId: 'chem_ch3',
            weight: 2,
            questionCount: 4,
            difficulty: 'Easy',
          ),
        ],
      ),
      Chapter(
        id: 'chem_ch4',
        name: 'Chemical Bonding',
        subjectId: 'chem',
        description: 'Types of bonds and molecular structures',
        classLevel: 'Class 11',
        weight: 3,
        topics: [
          Topic(
            id: 'chem_ch4_t1',
            name: 'Ionic & Covalent Bonding',
            chapterId: 'chem_ch4',
            weight: 2,
            questionCount: 4,
            difficulty: 'Medium',
          ),
          Topic(
            id: 'chem_ch4_t2',
            name: 'Molecular Geometry & VSEPR',
            chapterId: 'chem_ch4',
            weight: 2,
            questionCount: 3,
            difficulty: 'Hard',
          ),
        ],
      ),
    ],
  ),
  Subject(
    id: 'phys',
    name: 'Physics',
    icon: '⚛️',
    chapters: [
      Chapter(
        id: 'phys_ch1',
        name: 'Motion in One Dimension',
        subjectId: 'phys',
        description: 'Kinematics and equations of motion',
        classLevel: 'Class 11',
        weight: 2,
        topics: [
          Topic(
            id: 'phys_ch1_t1',
            name: 'Kinematics & Equations of Motion',
            chapterId: 'phys_ch1',
            weight: 2,
            questionCount: 4,
            difficulty: 'Easy',
          ),
          Topic(
            id: 'phys_ch1_t2',
            name: 'Relative Motion',
            chapterId: 'phys_ch1',
            weight: 1,
            questionCount: 2,
            difficulty: 'Medium',
          ),
        ],
      ),
      Chapter(
        id: 'phys_ch2',
        name: 'Laws of Motion',
        subjectId: 'phys',
        description: "Newton's laws and friction",
        classLevel: 'Class 11',
        weight: 3,
        topics: [
          Topic(
            id: 'phys_ch2_t1',
            name: "Newton's Laws & Force",
            chapterId: 'phys_ch2',
            weight: 3,
            questionCount: 5,
            difficulty: 'Medium',
          ),
          Topic(
            id: 'phys_ch2_t2',
            name: 'Friction & Normal Force',
            chapterId: 'phys_ch2',
            weight: 2,
            questionCount: 3,
            difficulty: 'Hard',
          ),
        ],
      ),
      Chapter(
        id: 'phys_ch3',
        name: 'Work, Energy & Power',
        subjectId: 'phys',
        description: 'Energy conservation and work theorem',
        classLevel: 'Class 11',
        weight: 2,
        topics: [
          Topic(
            id: 'phys_ch3_t1',
            name: 'Work & Kinetic Energy',
            chapterId: 'phys_ch3',
            weight: 2,
            questionCount: 4,
            difficulty: 'Easy',
          ),
          Topic(
            id: 'phys_ch3_t2',
            name: 'Potential Energy & Power',
            chapterId: 'phys_ch3',
            weight: 2,
            questionCount: 3,
            difficulty: 'Medium',
          ),
        ],
      ),
    ],
  ),
];

// ============= EXPANDED QUESTIONS (60+) =============

final List<Question> neetQuestionsPhase2 = [
  // ===== BIOLOGY =====
  Question(
    id: 1,
    subject: "Biology",
    chapter: "The Living World",
    topic: "Characteristics of Living Organisms",
    topicId: 'bio_ch1_t1',
    questionText: "Which of the following is the basic unit of classification?",
    options: ["Genus", "Species", "Kingdom", "Family"],
    correctAnswer: "Species",
    explanation:
        "Species is defined as a group of similar organisms capable of interbreeding and producing fertile offspring. It is the basic unit of classification.",
    ncertReference: "NCERT Class 11, Chapter 1, Page 10",
    year: 2023,
    difficulty: "Easy",
    tags: ["NCERT", "PYQ-2023", "Basic"],
  ),
  Question(
    id: 2,
    subject: "Biology",
    chapter: "The Living World",
    topic: "Characteristics of Living Organisms",
    topicId: 'bio_ch1_t1',
    questionText:
        "The ability of living organisms to undergo changes to suit their environment is called:",
    options: ["Adaptation", "Evolution", "Mutation", "Variation"],
    correctAnswer: "Adaptation",
    explanation:
        "Adaptation is the process by which organisms change to suit their environment, allowing better survival and reproduction.",
    ncertReference: "NCERT Class 11, Chapter 1, Page 12",
    year: 2022,
    difficulty: "Easy",
    tags: ["NCERT", "PYQ-2022"],
  ),
  Question(
    id: 3,
    subject: "Biology",
    chapter: "The Living World",
    topic: "Diversity in Living Organisms",
    topicId: 'bio_ch1_t2',
    questionText: "Taxonomy is the science of:",
    options: [
      "Classification of organisms",
      "Study of fossils",
      "Study of heredity",
      "Study of cells",
    ],
    correctAnswer: "Classification of organisms",
    explanation:
        "Taxonomy is the branch of biology that deals with the classification and naming of organisms.",
    ncertReference: "NCERT Class 11, Chapter 1, Page 8",
    year: 2023,
    difficulty: "Easy",
    tags: ["NCERT", "PYQ-2023"],
  ),
  Question(
    id: 4,
    subject: "Biology",
    chapter: "The Living World",
    topic: "Diversity in Living Organisms",
    topicId: 'bio_ch1_t2',
    questionText: "The number of kingdom proposed by Whittaker is:",
    options: ["2", "3", "4", "5"],
    correctAnswer: "5",
    explanation:
        "Whittaker proposed 5 kingdoms: Monera, Protista, Fungi, Plantae, and Animalia, based on cell type and mode of nutrition.",
    ncertReference: "NCERT Class 11, Chapter 1, Page 15",
    year: 2021,
    difficulty: "Medium",
    tags: ["NCERT", "PYQ-2021"],
  ),
  Question(
    id: 5,
    subject: "Biology",
    chapter: "Biological Classification",
    topic: "Monera & Protista",
    topicId: 'bio_ch2_t1',
    questionText: "Which of the following is a characteristic of bacteria?",
    options: [
      "Membrane-bound nucleus",
      "Peptidoglycan cell wall",
      "Mitochondria present",
      "Chloroplast present",
    ],
    correctAnswer: "Peptidoglycan cell wall",
    explanation:
        "Bacteria have a cell wall made of peptidoglycan, which is unique to prokaryotes. They lack membrane-bound organelles.",
    ncertReference: "NCERT Class 11, Chapter 2, Page 25",
    year: 2023,
    difficulty: "Medium",
    tags: ["NCERT", "PYQ-2023"],
  ),
  Question(
    id: 6,
    subject: "Biology",
    chapter: "Biological Classification",
    topic: "Monera & Protista",
    topicId: 'bio_ch2_t1',
    questionText: "Archaebacteria differ from eubacteria in having:",
    options: [
      "Cell wall without peptidoglycan",
      "Presence of nucleus",
      "Flagella structure",
      "All of the above",
    ],
    correctAnswer: "Cell wall without peptidoglycan",
    explanation:
        "Archaebacteria have cell walls that do not contain peptidoglycan, unlike eubacteria. This is one of their distinguishing features.",
    ncertReference: "NCERT Class 11, Chapter 2, Page 28",
    year: 2022,
    difficulty: "Hard",
    tags: ["NCERT", "PYQ-2022", "Advanced"],
  ),
  Question(
    id: 7,
    subject: "Biology",
    chapter: "Cell: The Unit of Life",
    topic: "Prokaryotic & Eukaryotic Cells",
    topicId: 'bio_ch3_t1',
    questionText: "The genetic material in prokaryotes is located in:",
    options: ["Nucleus", "Nucleoid region", "Chromosome", "Mitochondria"],
    correctAnswer: "Nucleoid region",
    explanation:
        "Prokaryotes lack a true nucleus. Their genetic material (DNA) is located in a region called the nucleoid, which is not membrane-bound.",
    ncertReference: "NCERT Class 11, Chapter 2, Page 32",
    year: 2023,
    difficulty: "Easy",
    tags: ["NCERT", "PYQ-2023"],
  ),
  Question(
    id: 8,
    subject: "Biology",
    chapter: "Cell: The Unit of Life",
    topic: "Prokaryotic & Eukaryotic Cells",
    topicId: 'bio_ch3_t1',
    questionText: "Which of the following organelles is not membrane-bound?",
    options: [
      "Mitochondria",
      "Ribosome",
      "Endoplasmic reticulum",
      "Golgi apparatus",
    ],
    correctAnswer: "Ribosome",
    explanation:
        "Ribosomes are not membrane-bound organelles. They are made of rRNA and proteins and are sites of protein synthesis.",
    ncertReference: "NCERT Class 11, Chapter 2, Page 40",
    year: 2023,
    difficulty: "Medium",
    tags: ["NCERT", "PYQ-2023"],
  ),
  Question(
    id: 9,
    subject: "Biology",
    chapter: "Cell: The Unit of Life",
    topic: "Cell Organelles",
    topicId: 'bio_ch3_t2',
    questionText:
        "Mitochondria are known as the powerhouse of the cell because:",
    options: [
      "They store energy",
      "They produce ATP through cellular respiration",
      "They contain DNA",
      "They synthesize proteins",
    ],
    correctAnswer: "They produce ATP through cellular respiration",
    explanation:
        "Mitochondria produce ATP (energy currency) through the process of cellular respiration, providing energy for all cellular activities.",
    ncertReference: "NCERT Class 11, Chapter 2, Page 45",
    year: 2024,
    difficulty: "Easy",
    tags: ["NCERT", "HighYield"],
  ),
  Question(
    id: 10,
    subject: "Biology",
    chapter: "Biomolecules",
    topic: "Carbohydrates & Lipids",
    topicId: 'bio_ch4_t1',
    questionText:
        "Which monosaccharide is the primary source of energy in cells?",
    options: ["Fructose", "Glucose", "Galactose", "Ribose"],
    correctAnswer: "Glucose",
    explanation:
        "Glucose is the primary source of cellular energy and is broken down in glycolysis and the citric acid cycle to produce ATP.",
    ncertReference: "NCERT Class 11, Chapter 3, Page 52",
    year: 2023,
    difficulty: "Easy",
    tags: ["NCERT", "PYQ-2023"],
  ),

  // ===== CHEMISTRY =====
  Question(
    id: 101,
    subject: "Chemistry",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Mole Concept & Calculations",
    topicId: 'chem_ch1_t1',
    questionText: "The number of atoms in 0.1 mole of a triatomic gas is?",
    options: ["6.022×10²²", "1.806×10²³", "3.6×10²³", "1.8×10²²"],
    correctAnswer: "1.806×10²³",
    explanation:
        "1 mole of any substance contains Avogadro's number (6.022×10²³) of particles. For a triatomic molecule with 0.1 mole: 0.1 × 3 × 6.022×10²³ = 1.806×10²³ atoms.",
    ncertReference: "NCERT Class 11, Chapter 1, Page 12",
    year: 2024,
    difficulty: "Medium",
    tags: ["NCERT", "PYQ-2024", "Calculation"],
  ),
  Question(
    id: 102,
    subject: "Chemistry",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Mole Concept & Calculations",
    topicId: 'chem_ch1_t1',
    questionText: "What is the molar mass of CO₂?",
    options: ["44 g/mol", "48 g/mol", "32 g/mol", "60 g/mol"],
    correctAnswer: "44 g/mol",
    explanation: "Molar mass of CO₂ = 12 (C) + 2×16 (O) = 12 + 32 = 44 g/mol",
    ncertReference: "NCERT Class 11, Chapter 1, Page 8",
    year: 2023,
    difficulty: "Easy",
    tags: ["NCERT", "PYQ-2023", "Basic"],
  ),
  Question(
    id: 103,
    subject: "Chemistry",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Stoichiometry",
    topicId: 'chem_ch1_t2',
    questionText: "In the reaction 2H₂ + O₂ → 2H₂O, the ratio of moles is:",
    options: ["2:1:1", "2:1:2", "1:1:2", "1:2:2"],
    correctAnswer: "2:1:2",
    explanation:
        "From the balanced equation: 2 moles H₂ react with 1 mole O₂ to produce 2 moles H₂O. Ratio = 2:1:2",
    ncertReference: "NCERT Class 11, Chapter 1, Page 20",
    year: 2022,
    difficulty: "Easy",
    tags: ["NCERT", "PYQ-2022"],
  ),
  Question(
    id: 104,
    subject: "Chemistry",
    chapter: "Structure of Atom",
    topic: "Bohr & Quantum Models",
    topicId: 'chem_ch2_t1',
    questionText:
        "Which model of atom proposed that electrons are embedded in a sphere of positive charge?",
    options: [
      "Dalton's model",
      "Thomson's model",
      "Rutherford's model",
      "Bohr's model",
    ],
    correctAnswer: "Thomson's model",
    explanation:
        "Thomson's plum pudding model proposed that electrons are embedded in a uniform sphere of positive charge, like plums in pudding.",
    ncertReference: "NCERT Class 11, Chapter 2, Page 28",
    year: 2022,
    difficulty: "Easy",
    tags: ["NCERT", "PYQ-2022", "History"],
  ),
  Question(
    id: 105,
    subject: "Chemistry",
    chapter: "Structure of Atom",
    topic: "Bohr & Quantum Models",
    topicId: 'chem_ch2_t1',
    questionText:
        "According to Bohr's model, the angular momentum of electron in ground state is:",
    options: ["h/4π", "h/2π", "h/π", "2h/π"],
    correctAnswer: "h/2π",
    explanation:
        "Bohr proposed that angular momentum = nh/2π, where n is the principal quantum number. For ground state (n=1), L = h/2π.",
    ncertReference: "NCERT Class 11, Chapter 2, Page 35",
    year: 2023,
    difficulty: "Hard",
    tags: ["NCERT", "PYQ-2023", "Advanced"],
  ),
  Question(
    id: 106,
    subject: "Chemistry",
    chapter: "Classification of Elements",
    topic: "Periodic Table & Periodicity",
    topicId: 'chem_ch3_t1',
    questionText: "Which of the following elements is most electronegative?",
    options: ["Oxygen", "Nitrogen", "Fluorine", "Chlorine"],
    correctAnswer: "Fluorine",
    explanation:
        "Fluorine has the highest electronegativity (3.98 on Pauling scale). Electronegativity increases across a period and up a group.",
    ncertReference: "NCERT Class 11, Chapter 3, Page 45",
    year: 2023,
    difficulty: "Easy",
    tags: ["NCERT", "PYQ-2023"],
  ),
  Question(
    id: 107,
    subject: "Chemistry",
    chapter: "Chemical Bonding",
    topic: "Ionic & Covalent Bonding",
    topicId: 'chem_ch4_t1',
    questionText: "An ionic bond forms between:",
    options: [
      "Two metals",
      "Two non-metals",
      "A metal and a non-metal",
      "An atom and a molecule",
    ],
    correctAnswer: "A metal and a non-metal",
    explanation:
        "An ionic bond forms through complete electron transfer from a metal (loses electrons) to a non-metal (gains electrons), resulting in electrostatic attraction.",
    ncertReference: "NCERT Class 11, Chapter 4, Page 62",
    year: 2024,
    difficulty: "Easy",
    tags: ["NCERT", "HighYield"],
  ),
  Question(
    id: 108,
    subject: "Chemistry",
    chapter: "Chemical Bonding",
    topic: "Molecular Geometry & VSEPR",
    topicId: 'chem_ch4_t2',
    questionText: "The shape of water (H₂O) molecule is:",
    options: ["Linear", "Bent/Angular", "Tetrahedral", "Trigonal planar"],
    correctAnswer: "Bent/Angular",
    explanation:
        "Water has a bent shape due to VSEPR theory. Oxygen has 2 bonding pairs and 2 lone pairs, resulting in a tetrahedral electron geometry but bent molecular geometry.",
    ncertReference: "NCERT Class 11, Chapter 4, Page 75",
    year: 2023,
    difficulty: "Medium",
    tags: ["NCERT", "PYQ-2023", "VSEPR"],
  ),

  // ===== PHYSICS =====
  Question(
    id: 201,
    subject: "Physics",
    chapter: "Motion in One Dimension",
    topic: "Kinematics & Equations of Motion",
    topicId: 'phys_ch1_t1',
    questionText: "What is the SI unit of acceleration?",
    options: ["m/s", "m/s²", "m²/s", "N/kg"],
    correctAnswer: "m/s²",
    explanation:
        "Acceleration is defined as the rate of change of velocity with respect to time. Its SI unit is meters per second squared (m/s²).",
    ncertReference: "NCERT Class 11, Chapter 3, Page 40",
    year: 2022,
    difficulty: "Easy",
    tags: ["NCERT", "PYQ-2022", "Units"],
  ),
  Question(
    id: 202,
    subject: "Physics",
    chapter: "Motion in One Dimension",
    topic: "Kinematics & Equations of Motion",
    topicId: 'phys_ch1_t1',
    questionText: "The equation v² = u² + 2as is derived from:",
    options: [
      "First equation of motion",
      "Second equation of motion",
      "Third equation of motion",
      "Newton's first law",
    ],
    correctAnswer: "Third equation of motion",
    explanation:
        "This is the third equation of motion for uniformly accelerated motion. It relates final velocity (v), initial velocity (u), acceleration (a), and displacement (s).",
    ncertReference: "NCERT Class 11, Chapter 3, Page 52",
    year: 2023,
    difficulty: "Easy",
    tags: ["NCERT", "PYQ-2023"],
  ),
  Question(
    id: 203,
    subject: "Physics",
    chapter: "Motion in One Dimension",
    topic: "Kinematics & Equations of Motion",
    topicId: 'phys_ch1_t1',
    questionText:
        "A body starting from rest travels distance of 2m in 2s. What is its acceleration?",
    options: ["0.5 m/s²", "1 m/s²", "2 m/s²", "4 m/s²"],
    correctAnswer: "1 m/s²",
    explanation:
        "Using s = ut + ½at², with u=0, s=2m, t=2s: 2 = 0 + ½a(4) => a = 1 m/s²",
    ncertReference: "NCERT Class 11, Chapter 3, Page 48",
    year: 2024,
    difficulty: "Easy",
    tags: ["NCERT", "Calculation"],
  ),
  Question(
    id: 204,
    subject: "Physics",
    chapter: "Motion in One Dimension",
    topic: "Relative Motion",
    topicId: 'phys_ch1_t2',
    questionText:
        "If two objects are moving in the same direction with velocities v₁ and v₂, their relative velocity is:",
    options: ["v₁ + v₂", "v₁ - v₂", "v₁ × v₂", "√(v₁² + v₂²)"],
    correctAnswer: "v₁ - v₂",
    explanation:
        "For objects moving in the same direction, relative velocity = |v₁ - v₂|. The relative velocity is the difference in their velocities.",
    ncertReference: "NCERT Class 11, Chapter 3, Page 58",
    year: 2023,
    difficulty: "Easy",
    tags: ["NCERT", "PYQ-2023"],
  ),
  Question(
    id: 205,
    subject: "Physics",
    chapter: "Laws of Motion",
    topic: "Newton's Laws & Force",
    topicId: 'phys_ch2_t1',
    questionText: "Newton's second law of motion defines:",
    options: ["Inertia", "Force", "Weight", "Momentum"],
    correctAnswer: "Force",
    explanation:
        "Newton's second law states F = ma, which defines force as the product of mass and acceleration. It relates force to the change in momentum.",
    ncertReference: "NCERT Class 11, Chapter 5, Page 85",
    year: 2023,
    difficulty: "Easy",
    tags: ["NCERT", "PYQ-2023"],
  ),
  Question(
    id: 206,
    subject: "Physics",
    chapter: "Laws of Motion",
    topic: "Newton's Laws & Force",
    topicId: 'phys_ch2_t1',
    questionText:
        "A 5 kg object is accelerated at 2 m/s². What force is applied to it?",
    options: ["2.5 N", "5 N", "10 N", "20 N"],
    correctAnswer: "10 N",
    explanation: "Using F = ma = 5 kg × 2 m/s² = 10 N",
    ncertReference: "NCERT Class 11, Chapter 5, Page 90",
    year: 2024,
    difficulty: "Easy",
    tags: ["NCERT", "Calculation"],
  ),
  Question(
    id: 207,
    subject: "Physics",
    chapter: "Laws of Motion",
    topic: "Friction & Normal Force",
    topicId: 'phys_ch2_t2',
    questionText: "Static friction is always:",
    options: [
      "Greater than kinetic friction",
      "Less than kinetic friction",
      "Equal to kinetic friction",
      "Zero on smooth surfaces",
    ],
    correctAnswer: "Greater than kinetic friction",
    explanation:
        "Static friction (maximum value) is always greater than kinetic friction for the same pair of surfaces. This is why it's harder to start moving an object than to keep it moving.",
    ncertReference: "NCERT Class 11, Chapter 5, Page 105",
    year: 2022,
    difficulty: "Medium",
    tags: ["NCERT", "PYQ-2022"],
  ),
  Question(
    id: 208,
    subject: "Physics",
    chapter: "Work, Energy & Power",
    topic: "Work & Kinetic Energy",
    topicId: 'phys_ch3_t1',
    questionText: "The work-energy theorem states that:",
    options: [
      "Work equals force times distance",
      "Net work equals change in kinetic energy",
      "Power equals work per unit time",
      "Energy is always conserved",
    ],
    correctAnswer: "Net work equals change in kinetic energy",
    explanation:
        "The work-energy theorem states W_net = ΔKE. The net work done on an object equals its change in kinetic energy.",
    ncertReference: "NCERT Class 11, Chapter 6, Page 125",
    year: 2023,
    difficulty: "Medium",
    tags: ["NCERT", "PYQ-2023", "Theorem"],
  ),
  Question(
    id: 209,
    subject: "Physics",
    chapter: "Work, Energy & Power",
    topic: "Potential Energy & Power",
    topicId: 'phys_ch3_t2',
    questionText: "Power is defined as:",
    options: [
      "Work done",
      "Rate of doing work",
      "Energy available",
      "Force applied",
    ],
    correctAnswer: "Rate of doing work",
    explanation:
        "Power is the rate of doing work. P = W/t, where W is work and t is time. SI unit is Watt (J/s).",
    ncertReference: "NCERT Class 11, Chapter 6, Page 138",
    year: 2022,
    difficulty: "Easy",
    tags: ["NCERT", "PYQ-2022"],
  ),
];
