import '../models/question_model.dart';

// ============= BIOLOGY (Class 11) =============
final List<Question> biologyQuestionsPhase2 = [
  Question(
    id: 23,
    subject: "Biology",
    chapter: "The Living World",
    topic: "Characteristics of Living Organisms",
    topicId: 'bio_ch1_t1',
    questionText: "The sum total of all the chemical reactions occurring in our body is called:",
    options: ["Metabolism", "Homeostasis", "Growth", "Reproduction"],
    correctAnswer: "Metabolism",
    explanation: "Metabolism is the sum total of all the chemical reactions occurring in the body, which includes both anabolism and catabolism.",
    ncertReference: "NCERT Class 11 Biology, Chapter 1",
    year: 2020,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 24,
    subject: "Biology",
    chapter: "The Living World",
    topic: "Characteristics of Living Organisms",
    topicId: 'bio_ch1_t1',
    questionText: "Increase in mass and increase in number of individuals are twin characteristics of:",
    options: ["Growth", "Reproduction", "Metabolism", "Adaptation"],
    correctAnswer: "Growth",
    explanation: "Growth is the increase in cell number and mass. In living organisms, growth and reproduction are twin characteristics as both increase the number of individuals.",
    ncertReference: "NCERT Class 11 Biology, Chapter 1",
    year: 2021,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 25,
    subject: "Biology",
    chapter: "The Living World",
    topic: "Diversity in Living Organisms",
    topicId: 'bio_ch1_t2',
    questionText: "The scientific name of humans is written as:",
    options: ["Homo sapiens", "homo Sapiens", "Homo Sapiens", "Homosapiens"],
    correctAnswer: "Homo sapiens",
    explanation: "In binomial nomenclature, the generic name starts with a capital letter and the specific epithet is written in lower case, both italicised.",
    ncertReference: "NCERT Class 11 Biology, Chapter 1",
    year: 2019,
    difficulty: "Medium",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 26,
    subject: "Biology",
    chapter: "The Living World",
    topic: "Diversity in Living Organisms",
    topicId: 'bio_ch1_t2',
    questionText: "The taxonomic category that is placed immediately above 'Order' is:",
    options: ["Class", "Family", "Genus", "Species"],
    correctAnswer: "Class",
    explanation: "The ascending order of taxonomic categories is: Species < Genus < Family < Order < Class < Phylum/Division < Kingdom.",
    ncertReference: "NCERT Class 11 Biology, Chapter 1",
    year: 2022,
    difficulty: "Medium",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 27,
    subject: "Biology",
    chapter: "Biological Classification",
    topic: "Monera & Protista",
    topicId: 'bio_ch2_t1',
    questionText: "Membrane-bound organelles are absent in:",
    options: ["Bacteria", "Amoeba", "Euglena", "Yeast"],
    correctAnswer: "Bacteria",
    explanation: "Bacteria are prokaryotes and lack membrane-bound organelles such as mitochondria, Golgi bodies and a true nucleus.",
    ncertReference: "NCERT Class 11 Biology, Chapter 2",
    year: 2020,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 28,
    subject: "Biology",
    chapter: "Biological Classification",
    topic: "Monera & Protista",
    topicId: 'bio_ch2_t1',
    questionText: "The cell wall of most bacteria is made up of:",
    options: ["Peptidoglycan", "Cellulose", "Chitin", "Pectin"],
    correctAnswer: "Peptidoglycan",
    explanation: "Bacterial cell walls are composed of peptidoglycan (murein), which is a polymer of sugars and amino acids.",
    ncertReference: "NCERT Class 11 Biology, Chapter 2",
    year: 2023,
    difficulty: "Medium",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 29,
    subject: "Biology",
    chapter: "Plant Kingdom",
    topic: "Algae",
    topicId: 'bio_ch3_t1',
    questionText: "The photosynthetic pigments present in green algae are:",
    options: [
      "Chlorophyll a and b",
      "Chlorophyll a only",
      "Phycoerythrin and chlorophyll a",
      "Phycocyanin only",
    ],
    correctAnswer: "Chlorophyll a and b",
    explanation: "Green algae (Chlorophyceae) contain chlorophyll a and b in the same proportion as higher plants, along with carotene and xanthophylls.",
    ncertReference: "NCERT Class 11 Biology, Chapter 3",
    year: 2018,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 30,
    subject: "Biology",
    chapter: "Plant Kingdom",
    topic: "Algae",
    topicId: 'bio_ch3_t1',
    questionText: "Chlorophyll-bearing, simple, thalloid, autotrophic plants are grouped under:",
    options: ["Algae", "Bryophytes", "Pteridophytes", "Gymnosperms"],
    correctAnswer: "Algae",
    explanation: "Algae are chlorophyll-bearing, simple, thalloid, largely aquatic, autotrophic organisms whose body is not differentiated into true tissues.",
    ncertReference: "NCERT Class 11 Biology, Chapter 3",
    year: 2021,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 31,
    subject: "Biology",
    chapter: "Animal Kingdom",
    topic: "Phylum Porifera",
    topicId: 'bio_ch4_t1',
    questionText: "Members of Phylum Porifera are characterized by the presence of a:",
    options: ["Canal system", "Metameric segmentation", "Notochord", "Jointed appendages"],
    correctAnswer: "Canal system",
    explanation: "The canal system is a characteristic feature of Porifera (sponges) through which water enters and leaves, facilitating food capture and gas exchange.",
    ncertReference: "NCERT Class 11 Biology, Chapter 4",
    year: 2019,
    difficulty: "Medium",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 32,
    subject: "Biology",
    chapter: "Animal Kingdom",
    topic: "Phylum Annelida",
    topicId: 'bio_ch4_t1',
    questionText: "The phylum that shows a closed circulatory system with a dorsal heart and a ventral nerve cord is:",
    options: ["Annelida", "Arthropoda", "Mollusca", "Echinodermata"],
    correctAnswer: "Annelida",
    explanation: "Annelids possess a closed circulatory system, and the dorsal vessel acts as the heart. The ventral nerve cord is another characteristic feature.",
    ncertReference: "NCERT Class 11 Biology, Chapter 4",
    year: 2022,
    difficulty: "Hard",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 33,
    subject: "Biology",
    chapter: "Cell: The Unit of Life",
    topic: "Eukaryotic Cell Organelles",
    topicId: 'bio_ch8_t1',
    questionText: "The double-membrane-bound organelle that possesses its own DNA is:",
    options: ["Mitochondria", "Lysosome", "Ribosome", "Golgi apparatus"],
    correctAnswer: "Mitochondria",
    explanation: "Mitochondria have a double membrane and contain their own circular DNA and ribosomes, making them semiautonomous organelles.",
    ncertReference: "NCERT Class 11 Biology, Chapter 8",
    year: 2020,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 34,
    subject: "Biology",
    chapter: "Cell: The Unit of Life",
    topic: "Eukaryotic Cell Organelles",
    topicId: 'bio_ch8_t1',
    questionText: "Ribosomes are composed of:",
    options: ["RNA and proteins", "DNA and proteins", "Only RNA", "Only proteins"],
    correctAnswer: "RNA and proteins",
    explanation: "Ribosomes are made up of ribosomal RNA (rRNA) and proteins, and are the site of protein synthesis.",
    ncertReference: "NCERT Class 11 Biology, Chapter 8",
    year: 2023,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 35,
    subject: "Biology",
    chapter: "Biomolecules",
    topic: "Enzymes",
    topicId: 'bio_ch9_t1',
    questionText: "The enzyme that catalyses the phosphorylation of glucose to glucose-6-phosphate is:",
    options: ["Hexokinase", "Phosphatase", "Aldolase", "Isomerase"],
    correctAnswer: "Hexokinase",
    explanation: "Hexokinase catalyses the conversion of glucose to glucose-6-phosphate in the first step of glycolysis, using one ATP.",
    ncertReference: "NCERT Class 11 Biology, Chapter 9",
    year: 2018,
    difficulty: "Medium",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 36,
    subject: "Biology",
    chapter: "Biomolecules",
    topic: "Structure of Macromolecules",
    topicId: 'bio_ch9_t1',
    questionText: "Amino acids are the monomers of:",
    options: ["Proteins", "Nucleic acids", "Lipids", "Polysaccharides"],
    correctAnswer: "Proteins",
    explanation: "Proteins are polymers of amino acids linked by peptide bonds.",
    ncertReference: "NCERT Class 11 Biology, Chapter 9",
    year: 2021,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 37,
    subject: "Biology",
    chapter: "Cell Cycle and Cell Division",
    topic: "Cell Cycle",
    topicId: 'bio_ch10_t1',
    questionText: "DNA replication occurs during which phase of the cell cycle?",
    options: ["S phase", "G1 phase", "G2 phase", "M phase"],
    correctAnswer: "S phase",
    explanation: "DNA synthesis (replication) takes place during the S (synthetic) phase of interphase, doubling the DNA content of the cell.",
    ncertReference: "NCERT Class 11 Biology, Chapter 10",
    year: 2020,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 38,
    subject: "Biology",
    chapter: "Cell Cycle and Cell Division",
    topic: "Meiosis",
    topicId: 'bio_ch10_t1',
    questionText: "The type of cell division that reduces the chromosome number by half is:",
    options: ["Meiosis", "Mitosis", "Amitosis", "Binary fission"],
    correctAnswer: "Meiosis",
    explanation: "Meiosis is a reductional division in which the chromosome number is halved, producing haploid gametes.",
    ncertReference: "NCERT Class 11 Biology, Chapter 10",
    year: 2022,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 39,
    subject: "Biology",
    chapter: "Photosynthesis in Higher Plants",
    topic: "Calvin Cycle",
    topicId: 'bio_ch13_t1',
    questionText: "The Calvin cycle is also known as:",
    options: ["C3 cycle", "C4 cycle", "Hatch-Slack cycle", "Krebs cycle"],
    correctAnswer: "C3 cycle",
    explanation: "The Calvin cycle is called the C3 cycle because the first stable product of CO2 fixation is a 3-carbon compound, 3-phosphoglyceric acid.",
    ncertReference: "NCERT Class 11 Biology, Chapter 13",
    year: 2019,
    difficulty: "Medium",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 40,
    subject: "Biology",
    chapter: "Photosynthesis in Higher Plants",
    topic: "Light Reaction",
    topicId: 'bio_ch13_t1',
    questionText: "The pigments involved in photosynthesis are located on the:",
    options: ["Thylakoid membranes", "Stroma", "Outer membrane", "Intermembrane space"],
    correctAnswer: "Thylakoid membranes",
    explanation: "Chlorophyll and other photosynthetic pigments are embedded in the thylakoid membranes of the chloroplast, organised into photosystems.",
    ncertReference: "NCERT Class 11 Biology, Chapter 13",
    year: 2023,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 41,
    subject: "Biology",
    chapter: "Respiration in Plants",
    topic: "Krebs Cycle",
    topicId: 'bio_ch14_t1',
    questionText: "The Krebs cycle operates in the:",
    options: ["Mitochondrial matrix", "Cytoplasm", "Chloroplast stroma", "Ribosomes"],
    correctAnswer: "Mitochondrial matrix",
    explanation: "The Krebs (citric acid) cycle takes place in the matrix of mitochondria, while the electron transport chain is located on the inner mitochondrial membrane.",
    ncertReference: "NCERT Class 11 Biology, Chapter 14",
    year: 2020,
    difficulty: "Medium",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 42,
    subject: "Biology",
    chapter: "Respiration in Plants",
    topic: "Electron Transport",
    topicId: 'bio_ch14_t1',
    questionText: "The final electron acceptor in aerobic respiration is:",
    options: ["Oxygen", "NAD+", "FAD", "Cytochrome"],
    correctAnswer: "Oxygen",
    explanation: "In aerobic respiration, oxygen is the terminal electron acceptor at the end of the electron transport chain.",
    ncertReference: "NCERT Class 11 Biology, Chapter 14",
    year: 2021,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
];

// ============= BIOLOGY (Class 12) =============
final List<Question> biologyQuestionsPhase2Class12 = [
  Question(
    id: 43,
    subject: "Biology",
    chapter: "Human Reproduction",
    topic: "Menstrual Cycle",
    topicId: 'bio_ch3_12_t1',
    questionText: "The release of a mature ovum from the Graafian follicle is called:",
    options: ["Ovulation", "Menstruation", "Implantation", "Parturition"],
    correctAnswer: "Ovulation",
    explanation: "Ovulation is the process by which a mature ovum is released from the Graafian follicle, triggered by an LH surge.",
    ncertReference: "NCERT Class 12 Biology, Chapter 3",
    year: 2019,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 44,
    subject: "Biology",
    chapter: "Human Reproduction",
    topic: "Spermatogenesis",
    topicId: 'bio_ch3_12_t1',
    questionText: "Spermatogenesis occurs in the:",
    options: ["Seminiferous tubules", "Epididymis", "Prostate gland", "Vas deferens"],
    correctAnswer: "Seminiferous tubules",
    explanation: "Spermatogenesis takes place in the seminiferous tubules of the testes, where germ cells divide to form spermatozoa.",
    ncertReference: "NCERT Class 12 Biology, Chapter 3",
    year: 2022,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 45,
    subject: "Biology",
    chapter: "Principles of Inheritance and Variation",
    topic: "Mendelian Inheritance",
    topicId: 'bio_ch5_12_t1',
    questionText: "When a single gene controls more than one phenotypic trait, the phenomenon is called:",
    options: ["Pleiotropy", "Polygeny", "Epistasis", "Codominance"],
    correctAnswer: "Pleiotropy",
    explanation: "Pleiotropy is the phenomenon where a single gene influences multiple, apparently unrelated, phenotypic traits.",
    ncertReference: "NCERT Class 12 Biology, Chapter 5",
    year: 2020,
    difficulty: "Medium",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 46,
    subject: "Biology",
    chapter: "Principles of Inheritance and Variation",
    topic: "Mendelian Inheritance",
    topicId: 'bio_ch5_12_t1',
    questionText: "Genes that are located on the same chromosome are called:",
    options: ["Linked genes", "Alleles", "Recombinants", "Loci"],
    correctAnswer: "Linked genes",
    explanation: "Linked genes are those present on the same chromosome and tend to be inherited together unless crossing over separates them.",
    ncertReference: "NCERT Class 12 Biology, Chapter 5",
    year: 2023,
    difficulty: "Medium",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 47,
    subject: "Biology",
    chapter: "Molecular Basis of Inheritance",
    topic: "DNA Replication",
    topicId: 'bio_ch6_12_t1',
    questionText: "The enzyme that adds nucleotides during DNA replication is:",
    options: ["DNA polymerase", "DNA ligase", "Helicase", "Primase"],
    correctAnswer: "DNA polymerase",
    explanation: "DNA polymerase adds nucleotides to the growing DNA strand in the 5' to 3' direction and also carries out proofreading.",
    ncertReference: "NCERT Class 12 Biology, Chapter 6",
    year: 2019,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 48,
    subject: "Biology",
    chapter: "Molecular Basis of Inheritance",
    topic: "Genetic Code",
    topicId: 'bio_ch6_12_t1',
    questionText: "The genetic code is said to be degenerate because:",
    options: [
      "More than one codon codes for a single amino acid",
      "One codon codes for more than one amino acid",
      "Codons are overlapping",
      "Codons are non-overlapping",
    ],
    correctAnswer: "More than one codon codes for a single amino acid",
    explanation: "Degeneracy of the genetic code means that several codons can specify the same amino acid.",
    ncertReference: "NCERT Class 12 Biology, Chapter 6",
    year: 2021,
    difficulty: "Medium",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 49,
    subject: "Biology",
    chapter: "Evolution",
    topic: "Origin of Life",
    topicId: 'bio_ch7_12_t1',
    questionText: "The Miller-Urey experiment demonstrated the formation of:",
    options: [
      "Organic molecules from inorganic precursors",
      "DNA from RNA",
      "Cells from macromolecules",
      "Oxygen in the primitive atmosphere",
    ],
    correctAnswer: "Organic molecules from inorganic precursors",
    explanation: "Miller and Urey passed an electric discharge through a mixture of methane, ammonia, hydrogen and water vapour, producing amino acids and other organic molecules.",
    ncertReference: "NCERT Class 12 Biology, Chapter 7",
    year: 2020,
    difficulty: "Medium",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 50,
    subject: "Biology",
    chapter: "Evolution",
    topic: "Homologous & Analogous Organs",
    topicId: 'bio_ch7_12_t1',
    questionText: "The wings of insects and the wings of birds are examples of:",
    options: ["Analogous organs", "Homologous organs", "Vestigial organs", "Atavism"],
    correctAnswer: "Analogous organs",
    explanation: "Wings of insects and birds have a similar function (flight) but different evolutionary origins, so they are analogous organs showing convergent evolution.",
    ncertReference: "NCERT Class 12 Biology, Chapter 7",
    year: 2022,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 51,
    subject: "Biology",
    chapter: "Human Health and Disease",
    topic: "Immunity",
    topicId: 'bio_ch8_12_t1',
    questionText: "The HIV virus primarily infects which cells of the immune system?",
    options: [
      "Helper T lymphocytes",
      "Red blood cells",
      "Bone marrow stem cells",
      "Neutrophils",
    ],
    correctAnswer: "Helper T lymphocytes",
    explanation: "HIV targets helper T (CD4+) lymphocytes, progressively destroying them and causing immunodeficiency.",
    ncertReference: "NCERT Class 12 Biology, Chapter 8",
    year: 2020,
    difficulty: "Medium",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 52,
    subject: "Biology",
    chapter: "Human Health and Disease",
    topic: "Common Diseases",
    topicId: 'bio_ch8_12_t1',
    questionText: "Malaria is caused by a protozoan belonging to the genus:",
    options: ["Plasmodium", "Trypanosoma", "Entamoeba", "Leishmania"],
    correctAnswer: "Plasmodium",
    explanation: "Malaria is caused by Plasmodium species (P. vivax, P. falciparum, etc.), transmitted by the female Anopheles mosquito.",
    ncertReference: "NCERT Class 12 Biology, Chapter 8",
    year: 2018,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 53,
    subject: "Biology",
    chapter: "Biotechnology: Principles and Processes",
    topic: "Tools of Recombinant DNA",
    topicId: 'bio_ch11_12_t1',
    questionText: "The enzyme used to join two DNA fragments together is:",
    options: ["DNA ligase", "Restriction endonuclease", "Exonuclease", "Gyrase"],
    correctAnswer: "DNA ligase",
    explanation: "DNA ligase seals the nicks between Okazaki fragments or between the insert and vector by forming phosphodiester bonds.",
    ncertReference: "NCERT Class 12 Biology, Chapter 11",
    year: 2021,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 54,
    subject: "Biology",
    chapter: "Biotechnology: Principles and Processes",
    topic: "Tools of Recombinant DNA",
    topicId: 'bio_ch11_12_t1',
    questionText: "Restriction endonucleases cut DNA at specific recognition sequences that are:",
    options: ["Palindromic", "Random", "Complementary", "Overlapping"],
    correctAnswer: "Palindromic",
    explanation: "Restriction enzymes recognise palindromic sequences, which read the same forward and backward on the two strands.",
    ncertReference: "NCERT Class 12 Biology, Chapter 11",
    year: 2023,
    difficulty: "Medium",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 55,
    subject: "Biology",
    chapter: "Organisms and Populations",
    topic: "Population Interactions",
    topicId: 'bio_ch13_12_t1',
    questionText: "The interaction between Cuscuta (dodder) and its host plant is an example of:",
    options: ["Parasitism", "Commensalism", "Mutualism", "Predation"],
    correctAnswer: "Parasitism",
    explanation: "Cuscuta is a parasitic plant that derives nutrition from its host plant, so the interaction is parasitism.",
    ncertReference: "NCERT Class 12 Biology, Chapter 13",
    year: 2019,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 56,
    subject: "Biology",
    chapter: "Ecosystem",
    topic: "Energy Flow",
    topicId: 'bio_ch14_12_t1',
    questionText: "The sequential order of energy flow in an ecosystem is:",
    options: [
      "Producers → Primary consumers → Secondary consumers",
      "Primary consumers → Producers → Secondary consumers",
      "Secondary consumers → Producers → Primary consumers",
      "Decomposers → Producers → Consumers",
    ],
    correctAnswer: "Producers → Primary consumers → Secondary consumers",
    explanation: "Energy flows unidirectionally in an ecosystem from producers to primary consumers to secondary consumers and beyond.",
    ncertReference: "NCERT Class 12 Biology, Chapter 14",
    year: 2020,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 57,
    subject: "Biology",
    chapter: "Biodiversity and Conservation",
    topic: "Biodiversity",
    topicId: 'bio_ch15_12_t1',
    questionText: "The term 'biodiversity' was popularised by:",
    options: ["E. O. Wilson", "Walter G. Rosen", "Odum", "Tansley"],
    correctAnswer: "E. O. Wilson",
    explanation: "Although Walter G. Rosen coined the term 'biodiversity', it was popularised by the ecologist Edward O. Wilson.",
    ncertReference: "NCERT Class 12 Biology, Chapter 15",
    year: 2021,
    difficulty: "Hard",
    tags: ["NCERT"],
    type: "mcq",
  ),
];

// ============= CHEMISTRY =============
final List<Question> chemistryQuestionsPhase2 = [
  Question(
    id: 103,
    subject: "Chemistry",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Mole Concept & Calculations",
    topicId: 'chem_ch1_t1',
    questionText: "The number of molecules present in one mole of CO2 is:",
    options: ["6.022×10²³", "3.011×10²³", "12.044×10²³", "6.022×10²²"],
    correctAnswer: "6.022×10²³",
    explanation: "One mole of any substance contains Avogadro's number (6.022×10²³) of particles.",
    ncertReference: "NCERT Class 11 Chemistry, Chapter 1",
    year: 2019,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 104,
    subject: "Chemistry",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Mole Concept & Calculations",
    topicId: 'chem_ch1_t1',
    questionText: "The molar mass of CaCO3 is:",
    options: ["100 g/mol", "56 g/mol", "84 g/mol", "92 g/mol"],
    correctAnswer: "100 g/mol",
    explanation: "Molar mass of CaCO3 = 40 (Ca) + 12 (C) + 3 × 16 (O) = 100 g/mol.",
    ncertReference: "NCERT Class 11 Chemistry, Chapter 1",
    year: 2020,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 105,
    subject: "Chemistry",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Mole Concept & Calculations",
    topicId: 'chem_ch1_t1',
    questionText: "The empirical formula of benzene (C6H6) is:",
    options: ["CH", "C6H6", "CH2", "C2H2"],
    correctAnswer: "CH",
    explanation: "The empirical formula is the simplest whole-number ratio of atoms. For C6H6, the ratio 6:6 simplifies to CH.",
    ncertReference: "NCERT Class 11 Chemistry, Chapter 1",
    year: 2022,
    difficulty: "Medium",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 106,
    subject: "Chemistry",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Mole Concept & Calculations",
    topicId: 'chem_ch1_t1',
    questionText: "At STP, one mole of any gas occupies a volume of:",
    options: ["22.4 L", "2.24 L", "44.8 L", "11.2 L"],
    correctAnswer: "22.4 L",
    explanation: "At STP (0 °C, 1 atm), the molar volume of any ideal gas is 22.4 litres.",
    ncertReference: "NCERT Class 11 Chemistry, Chapter 1",
    year: 2018,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 107,
    subject: "Chemistry",
    chapter: "Structure of Atom",
    topic: "Electronic Configuration",
    topicId: 'chem_ch2_t1',
    questionText: "The maximum number of electrons that can be accommodated in the third shell (n = 3) is:",
    options: ["18", "8", "32", "9"],
    correctAnswer: "18",
    explanation: "Maximum electrons in a shell = 2n². For n = 3, this is 2 × 9 = 18.",
    ncertReference: "NCERT Class 11 Chemistry, Chapter 2",
    year: 2020,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 108,
    subject: "Chemistry",
    chapter: "Structure of Atom",
    topic: "Quantum Numbers",
    topicId: 'chem_ch2_t1',
    questionText: "The azimuthal quantum number (l) for an s-orbital is:",
    options: ["0", "1", "2", "3"],
    correctAnswer: "0",
    explanation: "The azimuthal quantum number l takes values from 0 to (n - 1). For an s-orbital, l = 0.",
    ncertReference: "NCERT Class 11 Chemistry, Chapter 2",
    year: 2023,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 109,
    subject: "Chemistry",
    chapter: "Structure of Atom",
    topic: "Sub-atomic Particles",
    topicId: 'chem_ch2_t1',
    questionText: "The electron was discovered by:",
    options: ["J. J. Thomson", "Rutherford", "Chadwick", "Goldstein"],
    correctAnswer: "J. J. Thomson",
    explanation: "J. J. Thomson discovered the electron in 1897 through cathode ray experiments and determined its charge-to-mass ratio.",
    ncertReference: "NCERT Class 11 Chemistry, Chapter 2",
    year: 2021,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 110,
    subject: "Chemistry",
    chapter: "Structure of Atom",
    topic: "Quantum Numbers",
    topicId: 'chem_ch2_t1',
    questionText: "The subshell that can accommodate a maximum of 10 electrons is:",
    options: ["d", "s", "p", "f"],
    correctAnswer: "d",
    explanation: "A d-subshell has 5 orbitals, each holding 2 electrons, giving a maximum capacity of 10 electrons.",
    ncertReference: "NCERT Class 11 Chemistry, Chapter 2",
    year: 2019,
    difficulty: "Medium",
    tags: ["NCERT"],
    type: "mcq",
  ),
];

// ============= PHYSICS =============
final List<Question> physicsQuestionsPhase2 = [
  Question(
    id: 203,
    subject: "Physics",
    chapter: "Units and Measurements",
    topic: "SI Units",
    topicId: 'phys_ch2_t1',
    questionText: "The SI unit of electric charge is the:",
    options: ["Coulomb", "Ampere", "Volt", "Ohm"],
    correctAnswer: "Coulomb",
    explanation: "Charge is measured in coulombs (C); the ampere is the unit of current and the coulomb is defined as ampere-second.",
    ncertReference: "NCERT Class 11 Physics, Chapter 2",
    year: 2020,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 204,
    subject: "Physics",
    chapter: "Units and Measurements",
    topic: "Dimensions",
    topicId: 'phys_ch2_t1',
    questionText: "The dimensional formula of power is:",
    options: ["[ML²T⁻³]", "[MLT⁻²]", "[ML²T⁻²]", "[ML³T⁻³]"],
    correctAnswer: "[ML²T⁻³]",
    explanation: "Power = Work/Time = [ML²T⁻²]/[T] = [ML²T⁻³].",
    ncertReference: "NCERT Class 11 Physics, Chapter 2",
    year: 2022,
    difficulty: "Medium",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 205,
    subject: "Physics",
    chapter: "Units and Measurements",
    topic: "SI Units",
    topicId: 'phys_ch2_t1',
    questionText: "The SI unit of solid angle is the:",
    options: ["Steradian", "Radian", "Lux", "Pascal"],
    correctAnswer: "Steradian",
    explanation: "Solid angle is measured in steradians (sr), while the radian is the unit of plane angle.",
    ncertReference: "NCERT Class 11 Physics, Chapter 2",
    year: 2021,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 206,
    subject: "Physics",
    chapter: "Units and Measurements",
    topic: "Significant Figures",
    topicId: 'phys_ch2_t1',
    questionText: "The number of significant figures in the value 0.00250 is:",
    options: ["3", "4", "5", "2"],
    correctAnswer: "3",
    explanation: "Leading zeros are not significant, but the trailing zero is, so 0.00250 has 3 significant figures.",
    ncertReference: "NCERT Class 11 Physics, Chapter 2",
    year: 2023,
    difficulty: "Medium",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 207,
    subject: "Physics",
    chapter: "Motion in a Straight Line",
    topic: "Kinematics",
    topicId: 'phys_ch3_t1',
    questionText: "The slope of a velocity-time graph gives the:",
    options: ["Acceleration", "Displacement", "Speed", "Distance"],
    correctAnswer: "Acceleration",
    explanation: "Acceleration is the rate of change of velocity, which is the slope of a velocity-time graph.",
    ncertReference: "NCERT Class 11 Physics, Chapter 3",
    year: 2019,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 208,
    subject: "Physics",
    chapter: "Motion in a Straight Line",
    topic: "Kinematics",
    topicId: 'phys_ch3_t1',
    questionText: "The area under a velocity-time graph represents:",
    options: ["Displacement", "Acceleration", "Speed", "Force"],
    correctAnswer: "Displacement",
    explanation: "The area enclosed by the velocity-time graph and the time axis gives the displacement of the body.",
    ncertReference: "NCERT Class 11 Physics, Chapter 3",
    year: 2020,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 209,
    subject: "Physics",
    chapter: "Motion in a Straight Line",
    topic: "Kinematics",
    topicId: 'phys_ch3_t1',
    questionText: "A body moving with uniform velocity has an acceleration of:",
    options: ["Zero", "Constant non-zero", "Increasing", "Decreasing"],
    correctAnswer: "Zero",
    explanation: "Uniform velocity means no change in velocity over time, so acceleration is zero.",
    ncertReference: "NCERT Class 11 Physics, Chapter 3",
    year: 2022,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 210,
    subject: "Physics",
    chapter: "Motion in a Straight Line",
    topic: "Kinematics",
    topicId: 'phys_ch3_t1',
    questionText: "A body goes from point A to B and returns to A. The average velocity of the body is:",
    options: ["Zero", "Maximum", "Equal to average speed", "Negative"],
    correctAnswer: "Zero",
    explanation: "Average velocity = total displacement / total time. Since the body returns to its starting point, displacement is zero.",
    ncertReference: "NCERT Class 11 Physics, Chapter 3",
    year: 2021,
    difficulty: "Medium",
    tags: ["NCERT"],
    type: "mcq",
  ),
];
