import '../models/question_model.dart';
import '../models/subject_model.dart';

// ============= BIOLOGY QUESTIONS =============
final List<Question> biologyQuestions = [
  Question(
    id: 1,
    subject: "Biology",
    chapter: "The Living World",
    topic: "Characteristics of Living Organisms",
    topicId: 'bio_ch1_t1',
    questionText: "Which of the following is the basic unit of classification?",
    options: ["Genus", "Species", "Kingdom", "Family"],
    correctAnswer: "Species",
    explanation: "Species is defined as a group of similar organisms capable of interbreeding and producing fertile offspring. It is the basic unit of classification.",
    ncertReference: "NCERT Class 11, Chapter 1, Page 10",
    year: 2023,
    difficulty: "Easy",
    tags: ["NCERT", "PYQ-2023", "Basic"],
  ),
  Question(
    id: 2,
    subject: "Biology",
    chapter: "The Living World",
    topic: "Characteristics of Living Organisms",
    topicId: 'bio_ch1_t1',
    questionText: "The ability of living organisms to undergo changes to suit their environment is called:",
    options: ["Adaptation", "Evolution", "Mutation", "Variation"],
    correctAnswer: "Adaptation",
    explanation: "Adaptation is the process by which organisms change to suit their environment, allowing better survival and reproduction.",
    ncertReference: "NCERT Class 11, Chapter 1, Page 12",
    year: 2022,
    difficulty: "Easy",
    tags: ["NCERT", "PYQ-2022"],
  ),
  Question(
    id: 3,
    subject: "Biology",
    chapter: "The Living World",
    topic: "Diversity in Living Organisms",
    topicId: 'bio_ch1_t2',
    questionText: "Taxonomy is the science of:",
    options: ["Classification of organisms", "Study of fossils", "Study of heredity", "Study of cells"],
    correctAnswer: "Classification of organisms",
    explanation: "Taxonomy is the branch of biology that deals with the classification and naming of organisms.",
    ncertReference: "NCERT Class 11, Chapter 1, Page 8",
    year: 2023,
    difficulty: "Easy",
    tags: ["NCERT", "PYQ-2023"],
  ),
  Question(
    id: 4,
    subject: "Biology",
    chapter: "Biological Classification",
    topic: "Monera",
    topicId: 'bio_ch2_t1',
    questionText: "Archaebacteria differ from eubacteria in:",
    options: ["Cell membrane structure", "Mode of nutrition", "Cell shape", "Mode of reproduction"],
    correctAnswer: "Cell membrane structure",
    explanation: "Archaebacteria have a different cell wall structure and cell membrane structure (branched lipid chain) that helps them survive in extreme conditions.",
    ncertReference: "NCERT Class 11 Biology, Chapter 2",
    year: 2014,
    difficulty: "Medium",
    tags: ["PYQ", "NCERT"],
  ),
  Question(
    id: 5,
    subject: "Biology",
    chapter: "Plant Kingdom",
    topic: "Algae",
    topicId: 'bio_ch3_t1',
    questionText: "An example of colonial alga is:",
    options: ["Volvox", "Ulothrix", "Spirogyra", "Chlorella"],
    correctAnswer: "Volvox",
    explanation: "Volvox is a motile colonial freshwater green alga.",
    ncertReference: "NCERT Class 11 Biology, Chapter 3",
    year: 2017,
    difficulty: "Easy",
    tags: ["PYQ", "NCERT"],
  ),
  Question(
    id: 6,
    subject: "Biology",
    chapter: "Animal Kingdom",
    topic: "Phylum Chordata",
    topicId: 'bio_ch4_t1',
    questionText: "Which of the following characteristics is not shared by birds and mammals?",
    options: ["Viviparity", "Warm blooded nature", "Ossified endoskeleton", "Breathing using lungs"],
    correctAnswer: "Viviparity",
    explanation: "Most mammals are viviparous (give birth to live young), while all birds are oviparous (lay eggs).",
    ncertReference: "NCERT Class 11 Biology, Chapter 4",
    year: 2016,
    difficulty: "Medium",
    tags: ["PYQ"],
  ),
  Question(
    id: 7,
    subject: "Biology",
    chapter: "Cell: The Unit of Life",
    topic: "Prokaryotic Cells",
    topicId: 'bio_ch8_t1',
    questionText: "Which of the following is not a characteristic of prokaryotic cells?",
    options: ["Mesosome", "Circular DNA", "Photosynthetic lamellae", "Membrane bound organelles"],
    correctAnswer: "Membrane bound organelles",
    explanation: "Prokaryotic cells lack membrane-bound organelles like mitochondria, Golgi apparatus, etc.",
    ncertReference: "NCERT Class 11 Biology, Chapter 8",
    year: 2021,
    difficulty: "Easy",
    tags: ["NCERT"],
  ),
  Question(
    id: 8,
    subject: "Biology",
    chapter: "Biomolecules",
    topic: "Enzymes",
    topicId: 'bio_ch9_t1',
    questionText: "A non-proteinaceous enzyme is:",
    options: ["Lysozyme", "Ribozyme", "Ligase", "Deoxyribonuclease"],
    correctAnswer: "Ribozyme",
    explanation: "Ribozymes are RNA molecules that have catalytic activity.",
    ncertReference: "NCERT Class 11 Biology, Chapter 9",
    year: 2016,
    difficulty: "Medium",
    tags: ["PYQ"],
  ),
  Question(
    id: 9,
    subject: "Biology",
    chapter: "Cell Cycle and Cell Division",
    topic: "Meiosis",
    topicId: 'bio_ch10_t1',
    questionText: "Crossing over takes place during which stage of meiosis?",
    options: ["Pachytene", "Zygotene", "Leptotene", "Diplotene"],
    correctAnswer: "Pachytene",
    explanation: "Crossing over occurs between non-sister chromatids of homologous chromosomes during the pachytene stage of Prophase I.",
    ncertReference: "NCERT Class 11 Biology, Chapter 10",
    year: 2020,
    difficulty: "Medium",
    tags: ["PYQ", "NCERT"],
  ),
  Question(
    id: 10,
    subject: "Biology",
    chapter: "Photosynthesis in Higher Plants",
    topic: "Light Reaction",
    topicId: 'bio_ch13_t1',
    questionText: "The primary electron acceptor in PS II is:",
    options: ["Pheophytin", "Plastoquinone", "Cytochrome", "ATP"],
    correctAnswer: "Pheophytin",
    explanation: "In Photosystem II, the excited P680 transfers an electron to pheophytin.",
    ncertReference: "NCERT Class 11 Biology, Chapter 13",
    year: 2018,
    difficulty: "Hard",
    tags: ["PYQ"],
  ),
  Question(
    id: 11,
    subject: "Biology",
    chapter: "Respiration in Plants",
    topic: "Glycolysis",
    topicId: 'bio_ch14_t1',
    questionText: "The end product of glycolysis is:",
    options: ["Pyruvic acid", "Acetyl CoA", "Citric acid", "Lactic acid"],
    correctAnswer: "Pyruvic acid",
    explanation: "Glycolysis breaks down one molecule of glucose into two molecules of pyruvic acid.",
    ncertReference: "NCERT Class 11 Biology, Chapter 14",
    year: 2019,
    difficulty: "Easy",
    tags: ["NCERT"],
  ),
  Question(
    id: 12,
    subject: "Biology",
    chapter: "Human Reproduction",
    topic: "Menstrual Cycle",
    topicId: 'bio_ch3_12_t1',
    questionText: "The surge of which hormone triggers ovulation?",
    options: ["LH", "FSH", "Estrogen", "Progesterone"],
    correctAnswer: "LH",
    explanation: "A rapid surge of Luteinizing Hormone (LH) induces the rupture of Graafian follicle and release of ovum.",
    ncertReference: "NCERT Class 12 Biology, Chapter 3",
    year: 2020,
    difficulty: "Medium",
    tags: ["PYQ", "NCERT"],
  ),
  Question(
    id: 13,
    subject: "Biology",
    chapter: "Principles of Inheritance and Variation",
    topic: "Mendelian Inheritance",
    topicId: 'bio_ch5_12_t1',
    questionText: "The phenotypic ratio of a dihybrid cross in F2 generation is:",
    options: ["9:3:3:1", "3:1", "1:2:1", "1:1:1:1"],
    correctAnswer: "9:3:3:1",
    explanation: "Mendel's dihybrid cross resulted in a 9:3:3:1 ratio of phenotypes in the F2 generation.",
    ncertReference: "NCERT Class 12 Biology, Chapter 5",
    year: 2021,
    difficulty: "Easy",
    tags: ["NCERT"],
  ),
  Question(
    id: 14,
    subject: "Biology",
    chapter: "Molecular Basis of Inheritance",
    topic: "DNA Structure",
    topicId: 'bio_ch6_12_t1',
    questionText: "The pitch of DNA double helix is:",
    options: ["3.4 nm", "0.34 nm", "2 nm", "34 nm"],
    correctAnswer: "3.4 nm",
    explanation: "The pitch of the B-DNA helix is 3.4 nm, with about 10 base pairs per turn.",
    ncertReference: "NCERT Class 12 Biology, Chapter 6",
    year: 2022,
    difficulty: "Medium",
    tags: ["NCERT"],
  ),
  Question(
    id: 15,
    subject: "Biology",
    chapter: "Evolution",
    topic: "Homologous Structures",
    topicId: 'bio_ch7_12_t1',
    questionText: "Thorns of Bougainvillea and tendrils of Cucurbita are examples of:",
    options: ["Homologous organs", "Analogous organs", "Vestigial organs", "Atavism"],
    correctAnswer: "Homologous organs",
    explanation: "They both represent axillary bud modifications, hence are homologous despite performing different functions.",
    ncertReference: "NCERT Class 12 Biology, Chapter 7",
    year: 2017,
    difficulty: "Medium",
    tags: ["PYQ", "NCERT"],
  ),
  Question(
    id: 16,
    subject: "Biology",
    chapter: "Human Health and Disease",
    topic: "Immunity",
    topicId: 'bio_ch8_12_t1',
    questionText: "Which of the following is a primary lymphoid organ?",
    options: ["Bone marrow", "Spleen", "Peyer's patches", "Lymph nodes"],
    correctAnswer: "Bone marrow",
    explanation: "Bone marrow and thymus are primary lymphoid organs where lymphocytes mature.",
    ncertReference: "NCERT Class 12 Biology, Chapter 8",
    year: 2023,
    difficulty: "Easy",
    tags: ["NCERT"],
  ),
  Question(
    id: 17,
    subject: "Biology",
    chapter: "Biotechnology: Principles and Processes",
    topic: "Restriction Enzymes",
    topicId: 'bio_ch11_12_t1',
    questionText: "The 'molecular scissors' used in genetic engineering are:",
    options: ["Restriction endonucleases", "Ligases", "Polymerases", "Helicases"],
    correctAnswer: "Restriction endonucleases",
    explanation: "Restriction enzymes cut DNA at specific palindromic sequences.",
    ncertReference: "NCERT Class 12 Biology, Chapter 11",
    year: 2019,
    difficulty: "Easy",
    tags: ["NCERT"],
  ),
  Question(
    id: 18,
    subject: "Biology",
    chapter: "Organisms and Populations",
    topic: "Population Growth",
    topicId: 'bio_ch13_12_t1',
    questionText: "Which curve represents exponential growth?",
    options: ["J-shaped", "S-shaped", "Linear", "Bell-shaped"],
    correctAnswer: "J-shaped",
    explanation: "Exponential growth occurs when resources are unlimited, resulting in a J-shaped curve.",
    ncertReference: "NCERT Class 12 Biology, Chapter 13",
    year: 2020,
    difficulty: "Medium",
    tags: ["NCERT"],
  ),
  Question(
    id: 19,
    subject: "Biology",
    chapter: "Ecosystem",
    topic: "Energy Flow",
    topicId: 'bio_ch14_12_t1',
    questionText: "The 10% law of energy transfer was proposed by:",
    options: ["Lindeman", "Odum", "Tansley", "Reiter"],
    correctAnswer: "Lindeman",
    explanation: "Raymond Lindeman proposed the 10% law, stating only 10% energy is transferred to the next trophic level.",
    ncertReference: "NCERT Class 12 Biology, Chapter 14",
    year: 2021,
    difficulty: "Easy",
    tags: ["NCERT"],
  ),
  Question(
    id: 20,
    subject: "Biology",
    chapter: "Biodiversity and Conservation",
    topic: "In-situ Conservation",
    topicId: 'bio_ch15_12_t1',
    questionText: "Which of the following is not an in-situ conservation method?",
    options: ["Botanical gardens", "National parks", "Biosphere reserves", "Sacred groves"],
    correctAnswer: "Botanical gardens",
    explanation: "Botanical gardens are ex-situ conservation methods where plants are grown outside their natural habitat.",
    ncertReference: "NCERT Class 12 Biology, Chapter 15",
    year: 2022,
    difficulty: "Easy",
    tags: ["NCERT"],
  ),
];

// ============= CHEMISTRY QUESTIONS =============
final List<Question> chemistryQuestions = [
  Question(
    id: 101,
    subject: "Chemistry",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Mole Concept & Calculations",
    topicId: 'chem_ch1_t1',
    questionText: "The number of atoms in 0.1 mole of a triatomic gas is?",
    options: ["6.022×10²²", "1.806×10²³", "3.6×10²³", "1.8×10²²"],
    correctAnswer: "1.806×10²³",
    explanation: "1 mole of any substance contains Avogadro's number (6.022×10²³) of particles. For a triatomic molecule with 0.1 mole: 0.1 × 3 × 6.022×10²³ = 1.806×10²³ atoms.",
    ncertReference: "NCERT Class 11, Chapter 1, Page 12",
    year: 2024,
    difficulty: "Medium",
    tags: ["NCERT", "PYQ-2024", "Calculation"],
  ),
  Question(
    id: 102,
    subject: "Chemistry",
    chapter: "Structure of Atom",
    topic: "Quantum Numbers",
    topicId: 'chem_ch2_t1',
    questionText: "The total number of orbitals associated with third shell is:",
    options: ["9", "4", "16", "3"],
    correctAnswer: "9",
    explanation: "Number of orbitals = n². For n=3, number of orbitals = 3² = 9 (one 3s, three 3p, five 3d).",
    ncertReference: "NCERT Class 11 Chemistry, Chapter 2",
    year: 2021,
    difficulty: "Medium",
    tags: ["NCERT"],
  ),
  Question(
    id: 103,
    subject: "Chemistry",
    chapter: "Chemical Bonding",
    topic: "VSEPR Theory",
    topicId: 'chem_ch4_t1',
    questionText: "Which of the following has a linear shape?",
    options: ["CO₂", "H₂O", "SO₂", "NO₂"],
    correctAnswer: "CO₂",
    explanation: "CO₂ has sp hybridization and no lone pairs on central carbon, resulting in a linear shape.",
    ncertReference: "NCERT Class 11 Chemistry, Chapter 4",
    year: 2020,
    difficulty: "Easy",
    tags: ["NCERT"],
  ),
  Question(
    id: 104,
    subject: "Chemistry",
    chapter: "Thermodynamics",
    topic: "Entropy",
    topicId: 'chem_ch6_t1',
    questionText: "For a spontaneous process at all temperatures:",
    options: ["ΔH < 0, ΔS > 0", "ΔH > 0, ΔS < 0", "ΔH < 0, ΔS < 0", "ΔH > 0, ΔS > 0"],
    correctAnswer: "ΔH < 0, ΔS > 0",
    explanation: "Spontaneity depends on ΔG = ΔH - TΔS. If ΔH is negative and ΔS is positive, ΔG will always be negative.",
    ncertReference: "NCERT Class 11 Chemistry, Chapter 6",
    year: 2019,
    difficulty: "Medium",
    tags: ["NCERT"],
  ),
  Question(
    id: 105,
    subject: "Chemistry",
    chapter: "Equilibrium",
    topic: "Le Chatelier's Principle",
    topicId: 'chem_ch7_t1',
    questionText: "Increasing pressure in the reaction N₂ + 3H₂ ⇌ 2NH₃ favors:",
    options: ["Formation of NH₃", "Dissociation of NH₃", "No change", "Decrease in yield"],
    correctAnswer: "Formation of NH₃",
    explanation: "Increasing pressure favors the side with fewer moles of gas. Here, 4 moles of reactants produce 2 moles of products.",
    ncertReference: "NCERT Class 11 Chemistry, Chapter 7",
    year: 2018,
    difficulty: "Medium",
    tags: ["PYQ", "NCERT"],
  ),
  Question(
    id: 106,
    subject: "Chemistry",
    chapter: "Redox Reactions",
    topic: "Oxidation Number",
    topicId: 'chem_ch8_t1',
    questionText: "Oxidation number of Cr in K₂Cr₂O₇ is:",
    options: ["+6", "+3", "+5", "+7"],
    correctAnswer: "+6",
    explanation: "2(+1) + 2x + 7(-2) = 0 => 2x = 12 => x = +6.",
    ncertReference: "NCERT Class 11 Chemistry, Chapter 8",
    year: 2022,
    difficulty: "Easy",
    tags: ["NCERT"],
  ),
  Question(
    id: 107,
    subject: "Chemistry",
    chapter: "Organic Chemistry: Basic Principles",
    topic: "IUPAC Nomenclature",
    topicId: 'chem_ch12_t1',
    questionText: "The IUPAC name of CH₃COCH₃ is:",
    options: ["Propanone", "Ethanal", "Propanal", "Ethanone"],
    correctAnswer: "Propanone",
    explanation: "The molecule is a ketone with 3 carbons, hence propanone.",
    ncertReference: "NCERT Class 11 Chemistry, Chapter 12",
    year: 2023,
    difficulty: "Easy",
    tags: ["NCERT"],
  ),
  Question(
    id: 108,
    subject: "Chemistry",
    chapter: "Solutions",
    topic: "Raoult's Law",
    topicId: 'chem_ch2_12_t1',
    questionText: "An ideal solution follows Raoult's law over:",
    options: ["Entire range of concentration", "Low concentration only", "High concentration only", "Specific temperature only"],
    correctAnswer: "Entire range of concentration",
    explanation: "Ideal solutions obey Raoult's law at all concentrations and temperatures.",
    ncertReference: "NCERT Class 12 Chemistry, Chapter 2",
    year: 2021,
    difficulty: "Easy",
    tags: ["NCERT"],
  ),
  Question(
    id: 109,
    subject: "Chemistry",
    chapter: "Electrochemistry",
    topic: "Nernst Equation",
    topicId: 'chem_ch3_12_t1',
    questionText: "The unit of molar conductivity is:",
    options: ["S cm² mol⁻¹", "S cm⁻¹", "S cm mol⁻¹", "S cm²"],
    correctAnswer: "S cm² mol⁻¹",
    explanation: "Molar conductivity Λm = κ / C, unit is S cm² mol⁻¹.",
    ncertReference: "NCERT Class 12 Chemistry, Chapter 3",
    year: 2022,
    difficulty: "Medium",
    tags: ["NCERT"],
  ),
  Question(
    id: 110,
    subject: "Chemistry",
    chapter: "Chemical Kinetics",
    topic: "Order of Reaction",
    topicId: 'chem_ch4_12_t1',
    questionText: "The rate constant for a first order reaction has units:",
    options: ["s⁻¹", "mol L⁻¹ s⁻¹", "L mol⁻¹ s⁻¹", "mol L⁻¹"],
    correctAnswer: "s⁻¹",
    explanation: "For first order reaction, rate = k[A], so k = rate/[A] = (mol L⁻¹ s⁻¹) / (mol L⁻¹) = s⁻¹.",
    ncertReference: "NCERT Class 12 Chemistry, Chapter 4",
    year: 2020,
    difficulty: "Easy",
    tags: ["NCERT"],
  ),
  Question(
    id: 111,
    subject: "Chemistry",
    chapter: "Coordination Compounds",
    topic: "Ligands",
    topicId: 'chem_ch9_12_t1',
    questionText: "Which of the following is a bidentate ligand?",
    options: ["Oxalate", "Ammonia", "Water", "Cyanide"],
    correctAnswer: "Oxalate",
    explanation: "Oxalate (C₂O₄²⁻) can coordinate through two oxygen atoms.",
    ncertReference: "NCERT Class 12 Chemistry, Chapter 9",
    year: 2019,
    difficulty: "Medium",
    tags: ["NCERT"],
  ),
  Question(
    id: 112,
    subject: "Chemistry",
    chapter: "Haloalkanes and Haloarenes",
    topic: "SN2 Reaction",
    topicId: 'chem_ch10_12_t1',
    questionText: "Reactivity of alkyl halides towards SN2 follows order:",
    options: ["1° > 2° > 3°", "3° > 2° > 1°", "2° > 1° > 3°", "1° > 3° > 2°"],
    correctAnswer: "1° > 2° > 3°",
    explanation: "SN2 reaction involves backside attack, so less steric hindrance in primary halides favors reactivity.",
    ncertReference: "NCERT Class 12 Chemistry, Chapter 10",
    year: 2020,
    difficulty: "Medium",
    tags: ["PYQ", "NCERT"],
  ),
  Question(
    id: 113,
    subject: "Chemistry",
    chapter: "Alcohols, Phenols and Ethers",
    topic: "Acidity of Phenols",
    topicId: 'chem_ch11_12_t1',
    questionText: "Phenol is more acidic than:",
    options: ["Ethanol", "o-Nitrophenol", "p-Nitrophenol", "Picric acid"],
    correctAnswer: "Ethanol",
    explanation: "Phenoxide ion is resonance stabilized, making phenol more acidic than alcohols like ethanol.",
    ncertReference: "NCERT Class 12 Chemistry, Chapter 11",
    year: 2018,
    difficulty: "Medium",
    tags: ["NCERT"],
  ),
  Question(
    id: 114,
    subject: "Chemistry",
    chapter: "Aldehydes, Ketones and Carboxylic Acids",
    topic: "Nucleophilic Addition",
    topicId: 'chem_ch12_12_t1',
    questionText: "Cannizzaro reaction is given by:",
    options: ["Formaldehyde", "Acetaldehyde", "Acetone", "Propanal"],
    correctAnswer: "Formaldehyde",
    explanation: "Cannizzaro reaction is given by aldehydes which do not have an α-hydrogen atom.",
    ncertReference: "NCERT Class 12 Chemistry, Chapter 12",
    year: 2017,
    difficulty: "Hard",
    tags: ["PYQ"],
  ),
  Question(
    id: 115,
    subject: "Chemistry",
    chapter: "Biomolecules",
    topic: "Carbohydrates",
    topicId: 'chem_ch14_12_t1',
    questionText: "Which of the following is a non-reducing sugar?",
    options: ["Sucrose", "Glucose", "Fructose", "Maltose"],
    correctAnswer: "Sucrose",
    explanation: "Sucrose is non-reducing because its reducing groups (anomeric carbons) are involved in glycosidic linkage.",
    ncertReference: "NCERT Class 12 Chemistry, Chapter 14",
    year: 2022,
    difficulty: "Medium",
    tags: ["NCERT"],
  ),
];

// ============= PHYSICS QUESTIONS =============
final List<Question> physicsQuestions = [
  Question(
    id: 201,
    subject: "Physics",
    chapter: "Units and Measurements",
    topic: "Dimensions",
    topicId: 'phys_ch2_t1',
    questionText: "The dimensional formula for gravitational constant G is:",
    options: ["[M⁻¹L³T⁻²]", "[ML³T⁻²]", "[M⁻¹L²T⁻²]", "[ML²T⁻²]"],
    correctAnswer: "[M⁻¹L³T⁻²]",
    explanation: "F = G m1m2 / r² => G = F r² / m1m2. Units: [MLT⁻²][L²] / [M²] = [M⁻¹L³T⁻²].",
    ncertReference: "NCERT Class 11 Physics, Chapter 2",
    year: 2023,
    difficulty: "Medium",
    tags: ["NCERT", "PYQ"],
  ),
  Question(
    id: 202,
    subject: "Physics",
    chapter: "Motion in a Straight Line",
    topic: "Kinematics",
    topicId: 'phys_ch3_t1',
    questionText: "For a body falling freely under gravity, distance covered in time t is proportional to:",
    options: ["t²", "t", "√t", "t³"],
    correctAnswer: "t²",
    explanation: "s = ut + ½gt². For free fall u=0, so s = ½gt² => s ∝ t².",
    ncertReference: "NCERT Class 11 Physics, Chapter 3",
    year: 2022,
    difficulty: "Easy",
    tags: ["NCERT"],
  ),
  Question(
    id: 203,
    subject: "Physics",
    chapter: "Laws of Motion",
    topic: "Newton's Second Law",
    topicId: 'phys_ch5_t1',
    questionText: "Newton's second law gives the measure of:",
    options: ["Force", "Inertia", "Momentum", "Acceleration"],
    correctAnswer: "Force",
    explanation: "F = ma. Newton's second law states force is proportional to rate of change of momentum.",
    ncertReference: "NCERT Class 11 Physics, Chapter 5",
    year: 2021,
    difficulty: "Easy",
    tags: ["NCERT"],
  ),
  Question(
    id: 204,
    subject: "Physics",
    chapter: "Work, Energy and Power",
    topic: "Work-Energy Theorem",
    topicId: 'phys_ch6_t1',
    questionText: "Work done by a conservative force depends on:",
    options: ["Initial and final positions", "Path followed", "Time taken", "Velocity"],
    correctAnswer: "Initial and final positions",
    explanation: "Conservative forces like gravity are path independent.",
    ncertReference: "NCERT Class 11 Physics, Chapter 6",
    year: 2020,
    difficulty: "Easy",
    tags: ["NCERT"],
  ),
  Question(
    id: 205,
    subject: "Physics",
    chapter: "Gravitation",
    topic: "Escape Velocity",
    topicId: 'phys_ch8_t1',
    questionText: "Escape velocity from earth is approximately:",
    options: ["11.2 km/s", "8 km/s", "42 km/s", "9.8 km/s"],
    correctAnswer: "11.2 km/s",
    explanation: "v_e = √(2GM/R) ≈ 11.2 km/s for Earth.",
    ncertReference: "NCERT Class 11 Physics, Chapter 8",
    year: 2019,
    difficulty: "Easy",
    tags: ["NCERT"],
  ),
  Question(
    id: 206,
    subject: "Physics",
    chapter: "Thermodynamics",
    topic: "First Law",
    topicId: 'phys_ch12_t1',
    questionText: "In an isothermal process, which of the following is constant?",
    options: ["Temperature", "Pressure", "Volume", "Heat"],
    correctAnswer: "Temperature",
    explanation: "Isothermal means 'equal temperature'.",
    ncertReference: "NCERT Class 11 Physics, Chapter 12",
    year: 2018,
    difficulty: "Easy",
    tags: ["NCERT"],
  ),
  Question(
    id: 207,
    subject: "Physics",
    chapter: "Electrostatics",
    topic: "Coulomb's Law",
    topicId: 'phys_ch1_12_t1',
    questionText: "Force between two charges is inversely proportional to:",
    options: ["Square of distance", "Distance", "Product of charges", "Permittivity"],
    correctAnswer: "Square of distance",
    explanation: "F = k q1q2 / r², so F ∝ 1/r².",
    ncertReference: "NCERT Class 12 Physics, Chapter 1",
    year: 2023,
    difficulty: "Easy",
    tags: ["NCERT"],
  ),
  Question(
    id: 208,
    subject: "Physics",
    chapter: "Current Electricity",
    topic: "Ohm's Law",
    topicId: 'phys_ch3_12_t1',
    questionText: "Drift velocity of electrons is of the order of:",
    options: ["10⁻⁴ m/s", "10⁶ m/s", "10⁸ m/s", "1 m/s"],
    correctAnswer: "10⁻⁴ m/s",
    explanation: "Drift velocity is very small compared to thermal velocity.",
    ncertReference: "NCERT Class 12 Physics, Chapter 3",
    year: 2022,
    difficulty: "Medium",
    tags: ["NCERT"],
  ),
  Question(
    id: 209,
    subject: "Physics",
    chapter: "Moving Charges and Magnetism",
    topic: "Lorentz Force",
    topicId: 'phys_ch4_12_t1',
    questionText: "Force on a charge q moving with velocity v in magnetic field B is:",
    options: ["q(v × B)", "q(v . B)", "qvB", "qB/v"],
    correctAnswer: "q(v × B)",
    explanation: "Magnetic Lorentz force F = q(v × B).",
    ncertReference: "NCERT Class 12 Physics, Chapter 4",
    year: 2021,
    difficulty: "Medium",
    tags: ["NCERT"],
  ),
  Question(
    id: 210,
    subject: "Physics",
    chapter: "Electromagnetic Induction",
    topic: "Faraday's Law",
    topicId: 'phys_ch6_12_t1',
    questionText: "Lenz's law is a consequence of law of conservation of:",
    options: ["Energy", "Charge", "Momentum", "Mass"],
    correctAnswer: "Energy",
    explanation: "Lenz's law ensures that work must be done to change magnetic flux, consistent with energy conservation.",
    ncertReference: "NCERT Class 12 Physics, Chapter 6",
    year: 2020,
    difficulty: "Medium",
    tags: ["NCERT", "PYQ"],
  ),
  Question(
    id: 211,
    subject: "Physics",
    chapter: "Ray Optics",
    topic: "Refractive Index",
    topicId: 'phys_ch9_12_t1',
    questionText: "The critical angle for a medium with refractive index √2 is:",
    options: ["45°", "30°", "60°", "90°"],
    correctAnswer: "45°",
    explanation: "sin C = 1/n = 1/√2 => C = 45°.",
    ncertReference: "NCERT Class 12 Physics, Chapter 9",
    year: 2019,
    difficulty: "Medium",
    tags: ["NCERT"],
  ),
  Question(
    id: 212,
    subject: "Physics",
    chapter: "Wave Optics",
    topic: "Interference",
    topicId: 'phys_ch10_12_t1',
    questionText: "In Young's double slit experiment, fringe width is proportional to:",
    options: ["Wavelength", "Slit separation", "1/Wavelength", "1/Distance to screen"],
    correctAnswer: "Wavelength",
    explanation: "β = λD/d, so β ∝ λ.",
    ncertReference: "NCERT Class 12 Physics, Chapter 10",
    year: 2018,
    difficulty: "Medium",
    tags: ["NCERT"],
  ),
  Question(
    id: 213,
    subject: "Physics",
    chapter: "Dual Nature of Radiation",
    topic: "Photoelectric Effect",
    topicId: 'phys_ch11_12_t1',
    questionText: "Stopping potential depends on:",
    options: ["Frequency of incident light", "Intensity of light", "Distance from source", "Surface area"],
    correctAnswer: "Frequency of incident light",
    explanation: "eV₀ = hν - Φ. Stopping potential V₀ depends on frequency ν.",
    ncertReference: "NCERT Class 12 Physics, Chapter 11",
    year: 2023,
    difficulty: "Medium",
    tags: ["NCERT", "PYQ"],
  ),
  Question(
    id: 214,
    subject: "Physics",
    chapter: "Atoms",
    topic: "Bohr's Model",
    topicId: 'phys_ch12_12_t1',
    questionText: "Radius of nth orbit in hydrogen atom is proportional to:",
    options: ["n²", "n", "1/n", "1/n²"],
    correctAnswer: "n²",
    explanation: "r_n = a₀ n² / Z.",
    ncertReference: "NCERT Class 12 Physics, Chapter 12",
    year: 2021,
    difficulty: "Easy",
    tags: ["NCERT"],
  ),
  Question(
    id: 215,
    subject: "Physics",
    chapter: "Semiconductors",
    topic: "P-N Junction",
    topicId: 'phys_ch14_12_t1',
    questionText: "In reverse bias, depletion layer width:",
    options: ["Increases", "Decreases", "Remains same", "Becomes zero"],
    correctAnswer: "Increases",
    explanation: "Reverse bias pulls majority carriers away from the junction, increasing depletion width.",
    ncertReference: "NCERT Class 12 Physics, Chapter 14",
    year: 2022,
    difficulty: "Easy",
    tags: ["NCERT"],
  ),
];

// ============= SUBJECT STRUCTURE =============
final List<Subject> subjects = [
  Subject(
    id: 'bio',
    name: 'Biology',
    icon: '🧬',
    description: 'The study of living organisms and their interactions',
    chapters: [
      Chapter(
        id: 'bio_ch1',
        name: 'The Living World',
        subjectId: 'bio',
        description: 'Introduction to living organisms and taxonomy',
        classLevel: 'Class 11',
        weight: 1,
        topics: [
          Topic(id: 'bio_ch1_t1', name: 'Characteristics of Living Organisms', chapterId: 'bio_ch1', questionCount: 2, difficulty: 'Easy'),
          Topic(id: 'bio_ch1_t2', name: 'Diversity in Living Organisms', chapterId: 'bio_ch1', questionCount: 2, difficulty: 'Medium'),
        ],
      ),
      Chapter(id: 'bio_ch2', name: 'Biological Classification', subjectId: 'bio', classLevel: 'Class 11', weight: 2, topics: [Topic(id: 'bio_ch2_t1', name: 'Monera & Protista', chapterId: 'bio_ch2', questionCount: 1, difficulty: 'Medium')]),
      Chapter(id: 'bio_ch3', name: 'Plant Kingdom', subjectId: 'bio', classLevel: 'Class 11', weight: 2, topics: [Topic(id: 'bio_ch3_t1', name: 'Algae', chapterId: 'bio_ch3', questionCount: 1, difficulty: 'Easy')]),
      Chapter(id: 'bio_ch4', name: 'Animal Kingdom', subjectId: 'bio', classLevel: 'Class 11', weight: 3, topics: [Topic(id: 'bio_ch4_t1', name: 'Phylum Chordata', chapterId: 'bio_ch4', questionCount: 1, difficulty: 'Medium')]),
      Chapter(id: 'bio_ch8', name: 'Cell: The Unit of Life', subjectId: 'bio', classLevel: 'Class 11', weight: 3, topics: [Topic(id: 'bio_ch8_t1', name: 'Prokaryotic Cells', chapterId: 'bio_ch8', questionCount: 1, difficulty: 'Easy')]),
      Chapter(id: 'bio_ch9', name: 'Biomolecules', subjectId: 'bio', classLevel: 'Class 11', weight: 2, topics: [Topic(id: 'bio_ch9_t1', name: 'Enzymes', chapterId: 'bio_ch9', questionCount: 1, difficulty: 'Medium')]),
      Chapter(id: 'bio_ch10', name: 'Cell Cycle and Cell Division', subjectId: 'bio', classLevel: 'Class 11', weight: 3, topics: [Topic(id: 'bio_ch10_t1', name: 'Meiosis', chapterId: 'bio_ch10', questionCount: 1, difficulty: 'Medium')]),
      Chapter(id: 'bio_ch13', name: 'Photosynthesis in Higher Plants', subjectId: 'bio', classLevel: 'Class 11', weight: 3, topics: [Topic(id: 'bio_ch13_t1', name: 'Light Reaction', chapterId: 'bio_ch13', questionCount: 1, difficulty: 'Hard')]),
      Chapter(id: 'bio_ch14', name: 'Respiration in Plants', subjectId: 'bio', classLevel: 'Class 11', weight: 2, topics: [Topic(id: 'bio_ch14_t1', name: 'Glycolysis', chapterId: 'bio_ch14', questionCount: 1, difficulty: 'Easy')]),
      Chapter(id: 'bio_ch3_12', name: 'Human Reproduction', subjectId: 'bio', classLevel: 'Class 12', weight: 4, topics: [Topic(id: 'bio_ch3_12_t1', name: 'Menstrual Cycle', chapterId: 'bio_ch3_12', questionCount: 1, difficulty: 'Medium')]),
      Chapter(id: 'bio_ch5_12', name: 'Principles of Inheritance', subjectId: 'bio', classLevel: 'Class 12', weight: 4, topics: [Topic(id: 'bio_ch5_12_t1', name: 'Mendelian Inheritance', chapterId: 'bio_ch5_12', questionCount: 1, difficulty: 'Easy')]),
      Chapter(id: 'bio_ch6_12', name: 'Molecular Basis of Inheritance', subjectId: 'bio', classLevel: 'Class 12', weight: 5, topics: [Topic(id: 'bio_ch6_12_t1', name: 'DNA Structure', chapterId: 'bio_ch6_12', questionCount: 1, difficulty: 'Medium')]),
      Chapter(id: 'bio_ch7_12', name: 'Evolution', subjectId: 'bio', classLevel: 'Class 12', weight: 2, topics: [Topic(id: 'bio_ch7_12_t1', name: 'Homologous Structures', chapterId: 'bio_ch7_12', questionCount: 1, difficulty: 'Medium')]),
      Chapter(id: 'bio_ch8_12', name: 'Human Health and Disease', subjectId: 'bio', classLevel: 'Class 12', weight: 3, topics: [Topic(id: 'bio_ch8_12_t1', name: 'Immunity', chapterId: 'bio_ch8_12', questionCount: 1, difficulty: 'Easy')]),
      Chapter(id: 'bio_ch11_12', name: 'Biotechnology: Principles', subjectId: 'bio', classLevel: 'Class 12', weight: 4, topics: [Topic(id: 'bio_ch11_12_t1', name: 'Restriction Enzymes', chapterId: 'bio_ch11_12', questionCount: 1, difficulty: 'Easy')]),
      Chapter(id: 'bio_ch13_12', name: 'Organisms and Populations', subjectId: 'bio', classLevel: 'Class 12', weight: 2, topics: [Topic(id: 'bio_ch13_12_t1', name: 'Population Growth', chapterId: 'bio_ch13_12', questionCount: 1, difficulty: 'Medium')]),
      Chapter(id: 'bio_ch14_12', name: 'Ecosystem', subjectId: 'bio', classLevel: 'Class 12', weight: 2, topics: [Topic(id: 'bio_ch14_12_t1', name: 'Energy Flow', chapterId: 'bio_ch14_12', questionCount: 1, difficulty: 'Easy')]),
      Chapter(id: 'bio_ch15_12', name: 'Biodiversity', subjectId: 'bio', classLevel: 'Class 12', weight: 2, topics: [Topic(id: 'bio_ch15_12_t1', name: 'In-situ Conservation', chapterId: 'bio_ch15_12', questionCount: 1, difficulty: 'Easy')]),
    ],
  ),
  Subject(
    id: 'chem',
    name: 'Chemistry',
    icon: '⚗️',
    description: 'The study of matter and its transformations',
    chapters: [
      Chapter(id: 'chem_ch1', name: 'Basic Concepts', subjectId: 'chem', classLevel: 'Class 11', weight: 2, topics: [Topic(id: 'chem_ch1_t1', name: 'Mole Concept', chapterId: 'chem_ch1', questionCount: 1, difficulty: 'Medium')]),
      Chapter(id: 'chem_ch2', name: 'Structure of Atom', subjectId: 'chem', classLevel: 'Class 11', weight: 2, topics: [Topic(id: 'chem_ch2_t1', name: 'Quantum Numbers', chapterId: 'chem_ch2', questionCount: 1, difficulty: 'Medium')]),
      Chapter(id: 'chem_ch4', name: 'Chemical Bonding', subjectId: 'chem', classLevel: 'Class 11', weight: 3, topics: [Topic(id: 'chem_ch4_t1', name: 'VSEPR Theory', chapterId: 'chem_ch4', questionCount: 1, difficulty: 'Easy')]),
      Chapter(id: 'chem_ch6', name: 'Thermodynamics', subjectId: 'chem', classLevel: 'Class 11', weight: 2, topics: [Topic(id: 'chem_ch6_t1', name: 'Entropy', chapterId: 'chem_ch6', questionCount: 1, difficulty: 'Medium')]),
      Chapter(id: 'chem_ch7', name: 'Equilibrium', subjectId: 'chem', classLevel: 'Class 11', weight: 3, topics: [Topic(id: 'chem_ch7_t1', name: 'Le Chatelier', chapterId: 'chem_ch7', questionCount: 1, difficulty: 'Medium')]),
      Chapter(id: 'chem_ch8', name: 'Redox Reactions', subjectId: 'chem', classLevel: 'Class 11', weight: 1, topics: [Topic(id: 'chem_ch8_t1', name: 'Oxidation Number', chapterId: 'chem_ch8', questionCount: 1, difficulty: 'Easy')]),
      Chapter(id: 'chem_ch12', name: 'Organic Chemistry: Basic', subjectId: 'chem', classLevel: 'Class 11', weight: 3, topics: [Topic(id: 'chem_ch12_t1', name: 'IUPAC Nomenclature', chapterId: 'chem_ch12', questionCount: 1, difficulty: 'Easy')]),
      Chapter(id: 'chem_ch2_12', name: 'Solutions', subjectId: 'chem', classLevel: 'Class 12', weight: 3, topics: [Topic(id: 'chem_ch2_12_t1', name: 'Raoult Law', chapterId: 'chem_ch2_12', questionCount: 1, difficulty: 'Easy')]),
      Chapter(id: 'chem_ch3_12', name: 'Electrochemistry', subjectId: 'chem', classLevel: 'Class 12', weight: 3, topics: [Topic(id: 'chem_ch3_12_t1', name: 'Nernst Equation', chapterId: 'chem_ch3_12', questionCount: 1, difficulty: 'Medium')]),
      Chapter(id: 'chem_ch4_12', name: 'Chemical Kinetics', subjectId: 'chem', classLevel: 'Class 12', weight: 3, topics: [Topic(id: 'chem_ch4_12_t1', name: 'Order of Reaction', chapterId: 'chem_ch4_12', questionCount: 1, difficulty: 'Easy')]),
      Chapter(id: 'chem_ch9_12', name: 'Coordination Compounds', subjectId: 'chem', classLevel: 'Class 12', weight: 3, topics: [Topic(id: 'chem_ch9_12_t1', name: 'Ligands', chapterId: 'chem_ch9_12', questionCount: 1, difficulty: 'Medium')]),
      Chapter(id: 'chem_ch10_12', name: 'Haloalkanes', subjectId: 'chem', classLevel: 'Class 12', weight: 3, topics: [Topic(id: 'chem_ch10_12_t1', name: 'SN2 Reaction', chapterId: 'chem_ch10_12', questionCount: 1, difficulty: 'Medium')]),
      Chapter(id: 'chem_ch11_12', name: 'Alcohols & Phenols', subjectId: 'chem', classLevel: 'Class 12', weight: 3, topics: [Topic(id: 'chem_ch11_12_t1', name: 'Acidity', chapterId: 'chem_ch11_12', questionCount: 1, difficulty: 'Medium')]),
      Chapter(id: 'chem_ch12_12', name: 'Aldehydes & Ketones', subjectId: 'chem', classLevel: 'Class 12', weight: 4, topics: [Topic(id: 'chem_ch12_12_t1', name: 'Cannizzaro', chapterId: 'chem_ch12_12', questionCount: 1, difficulty: 'Hard')]),
      Chapter(id: 'chem_ch14_12', name: 'Biomolecules', subjectId: 'chem', classLevel: 'Class 12', weight: 2, topics: [Topic(id: 'chem_ch14_12_t1', name: 'Carbohydrates', chapterId: 'chem_ch14_12', questionCount: 1, difficulty: 'Medium')]),
    ],
  ),
  Subject(
    id: 'phys',
    name: 'Physics',
    icon: '⚛️',
    description: 'The study of nature and its laws',
    chapters: [
      Chapter(id: 'phys_ch2', name: 'Units & Measurements', subjectId: 'phys', classLevel: 'Class 11', weight: 1, topics: [Topic(id: 'phys_ch2_t1', name: 'Dimensions', chapterId: 'phys_ch2', questionCount: 1, difficulty: 'Medium')]),
      Chapter(id: 'phys_ch3', name: 'Motion in Straight Line', subjectId: 'phys', classLevel: 'Class 11', weight: 2, topics: [Topic(id: 'phys_ch3_t1', name: 'Kinematics', chapterId: 'phys_ch3', questionCount: 1, difficulty: 'Easy')]),
      Chapter(id: 'phys_ch5', name: 'Laws of Motion', subjectId: 'phys', classLevel: 'Class 11', weight: 2, topics: [Topic(id: 'phys_ch5_t1', name: 'Newton Laws', chapterId: 'phys_ch5', questionCount: 1, difficulty: 'Easy')]),
      Chapter(id: 'phys_ch6', name: 'Work & Energy', subjectId: 'phys', classLevel: 'Class 11', weight: 2, topics: [Topic(id: 'phys_ch6_t1', name: 'Work-Energy', chapterId: 'phys_ch6', questionCount: 1, difficulty: 'Easy')]),
      Chapter(id: 'phys_ch8', name: 'Gravitation', subjectId: 'phys', classLevel: 'Class 11', weight: 2, topics: [Topic(id: 'phys_ch8_t1', name: 'Escape Velocity', chapterId: 'phys_ch8', questionCount: 1, difficulty: 'Easy')]),
      Chapter(id: 'phys_ch12', name: 'Thermodynamics', subjectId: 'phys', classLevel: 'Class 11', weight: 2, topics: [Topic(id: 'phys_ch12_t1', name: 'First Law', chapterId: 'phys_ch12', questionCount: 1, difficulty: 'Easy')]),
      Chapter(id: 'phys_ch1_12', name: 'Electrostatics', subjectId: 'phys', classLevel: 'Class 12', weight: 4, topics: [Topic(id: 'phys_ch1_12_t1', name: 'Coulomb Law', chapterId: 'phys_ch1_12', questionCount: 1, difficulty: 'Easy')]),
      Chapter(id: 'phys_ch3_12', name: 'Current Electricity', subjectId: 'phys', classLevel: 'Class 12', weight: 4, topics: [Topic(id: 'phys_ch3_12_t1', name: 'Ohm Law', chapterId: 'phys_ch3_12', questionCount: 1, difficulty: 'Medium')]),
      Chapter(id: 'phys_ch4_12', name: 'Moving Charges', subjectId: 'phys', classLevel: 'Class 12', weight: 3, topics: [Topic(id: 'phys_ch4_12_t1', name: 'Lorentz Force', chapterId: 'phys_ch4_12', questionCount: 1, difficulty: 'Medium')]),
      Chapter(id: 'phys_ch6_12', name: 'EMI', subjectId: 'phys', classLevel: 'Class 12', weight: 3, topics: [Topic(id: 'phys_ch6_12_t1', name: 'Faraday Law', chapterId: 'phys_ch6_12', questionCount: 1, difficulty: 'Medium')]),
      Chapter(id: 'phys_ch9_12', name: 'Ray Optics', subjectId: 'phys', classLevel: 'Class 12', weight: 4, topics: [Topic(id: 'phys_ch9_12_t1', name: 'Refractive Index', chapterId: 'phys_ch9_12', questionCount: 1, difficulty: 'Medium')]),
      Chapter(id: 'phys_ch10_12', name: 'Wave Optics', subjectId: 'phys', classLevel: 'Class 12', weight: 3, topics: [Topic(id: 'phys_ch10_12_t1', name: 'Interference', chapterId: 'phys_ch10_12', questionCount: 1, difficulty: 'Medium')]),
      Chapter(id: 'phys_ch11_12', name: 'Dual Nature', subjectId: 'phys', classLevel: 'Class 12', weight: 2, topics: [Topic(id: 'phys_ch11_12_t1', name: 'Photoelectric', chapterId: 'phys_ch11_12', questionCount: 1, difficulty: 'Medium')]),
      Chapter(id: 'phys_ch12_12', name: 'Atoms', subjectId: 'phys', classLevel: 'Class 12', weight: 2, topics: [Topic(id: 'phys_ch12_12_t1', name: 'Bohr Model', chapterId: 'phys_ch12_12', questionCount: 1, difficulty: 'Easy')]),
      Chapter(id: 'phys_ch14_12', name: 'Semiconductors', subjectId: 'phys', classLevel: 'Class 12', weight: 3, topics: [Topic(id: 'phys_ch14_12_t1', name: 'P-N Junction', chapterId: 'phys_ch14_12', questionCount: 1, difficulty: 'Easy')]),
    ],
  ),
];

// Helper function to get all questions as flat list for database
List<Question> getAllQuestions() {
  return [...biologyQuestions, ...chemistryQuestions, ...physicsQuestions];
}

// Helper function to get questions for a specific topic
List<Question> getQuestionsForTopic(String topicId) {
  final allQuestions = getAllQuestions();
  return allQuestions.where((q) => q.topicId == topicId).toList();
}
