import '../models/question_model.dart';
import '../models/subject_model.dart';
import '../models/flashcard_model.dart';

// ============= FLASHCARDS =============
final List<Flashcard> sampleFlashcards = [
  Flashcard(
    id: 'f1',
    front: 'Powerhouse of the cell',
    back: 'Mitochondria',
    subject: 'Biology',
    topicId: 'bio_ch2_t1',
  ),
  Flashcard(
    id: 'f2',
    front: 'Avogadro\'s number value',
    back: '6.022 × 10²³',
    subject: 'Chemistry',
    topicId: 'chem_ch1_t1',
  ),
  Flashcard(
    id: 'f3',
    front: 'Unit of Force',
    back: 'Newton (N)',
    subject: 'Physics',
    topicId: 'phys_ch1_t1',
  ),
  Flashcard(
    id: 'f4',
    front: 'Father of Taxonomy',
    back: 'Carolus Linnaeus',
    subject: 'Biology',
    topicId: 'bio_ch1_t1',
  ),
];

// ============= BIOLOGY QUESTIONS =============
final List<Question> biologyQuestions = [
  Question(
    id: 1,
    subject: "Biology",
    chapter: "The Living World",
    topic: "Characteristics of Living Organisms",
    topicId: 'bio_ch1_t1',
    questionText: "Which of the following is the basic unit of classification?",
    options: ["Genus", "Species", "Kingdom", "Family"],
    correctAnswer: "Species",
    explanation: "Species is defined as a group of similar organisms capable of interbreeding and producing fertile offspring. It is the basic unit of classification.",
    ncertReference: "NCERT Class 11, Chapter 1, Page 10",
    year: 2023,
    difficulty: "Easy",
    tags: ["NCERT", "PYQ-2023", "Basic"],
    type: "mcq",
  ),
  Question(
    id: 2,
    subject: "Biology",
    chapter: "The Living World",
    topic: "Characteristics of Living Organisms",
    topicId: 'bio_ch1_t1',
    questionText: "The ability of living organisms to undergo changes to suit their environment is called:",
    options: ["Adaptation", "Evolution", "Mutation", "Variation"],
    correctAnswer: "Adaptation",
    explanation: "Adaptation is the process by which organisms change to suit their environment, allowing better survival and reproduction.",
    ncertReference: "NCERT Class 11, Chapter 1, Page 12",
    year: 2022,
    difficulty: "Easy",
    tags: ["NCERT", "PYQ-2022"],
    type: "mcq",
  ),
  Question(
    id: 3,
    subject: "Biology",
    chapter: "The Living World",
    topic: "Diversity in Living Organisms",
    topicId: 'bio_ch1_t2',
    questionText: "Taxonomy is the science of:",
    options: ["Classification of organisms", "Study of fossils", "Study of heredity", "Study of cells"],
    correctAnswer: "Classification of organisms",
    explanation: "Taxonomy is the branch of biology that deals with the classification and naming of organisms.",
    ncertReference: "NCERT Class 11, Chapter 1, Page 8",
    year: 2023,
    difficulty: "Easy",
    tags: ["NCERT", "PYQ-2023"],
    type: "mcq",
  ),
  Question(
    id: 4,
    subject: "Biology",
    chapter: "Biological Classification",
    topic: "Monera",
    topicId: 'bio_ch2_t1',
    questionText: "Archaebacteria differ from eubacteria in:",
    options: ["Cell membrane structure", "Mode of nutrition", "Cell shape", "Mode of reproduction"],
    correctAnswer: "Cell membrane structure",
    explanation: "Archaebacteria have a different cell wall structure and cell membrane structure (branched lipid chain) that helps them survive in extreme conditions.",
    ncertReference: "NCERT Class 11 Biology, Chapter 2",
    year: 2014,
    difficulty: "Medium",
    tags: ["PYQ", "NCERT"],
    type: "mcq",
  ),
  Question(
    id: 5,
    subject: "Biology",
    chapter: "Plant Kingdom",
    topic: "Algae",
    topicId: 'bio_ch3_t1',
    questionText: "An example of colonial alga is:",
    options: ["Volvox", "Ulothrix", "Spirogyra", "Chlorella"],
    correctAnswer: "Volvox",
    explanation: "Volvox is a motile colonial freshwater green alga.",
    ncertReference: "NCERT Class 11 Biology, Chapter 3",
    year: 2017,
    difficulty: "Easy",
    tags: ["PYQ", "NCERT"],
    type: "mcq",
  ),
  Question(
    id: 6,
    subject: "Biology",
    chapter: "Animal Kingdom",
    topic: "Phylum Chordata",
    topicId: 'bio_ch4_t1',
    questionText: "Which of the following characteristics is not shared by birds and mammals?",
    options: ["Viviparity", "Warm blooded nature", "Ossified endoskeleton", "Breathing using lungs"],
    correctAnswer: "Viviparity",
    explanation: "Most mammals are viviparous (give birth to live young), while all birds are oviparous (lay eggs).",
    ncertReference: "NCERT Class 11 Biology, Chapter 4",
    year: 2016,
    difficulty: "Medium",
    tags: ["PYQ"],
    type: "mcq",
  ),
  Question(
    id: 7,
    subject: "Biology",
    chapter: "Cell: The Unit of Life",
    topic: "Prokaryotic Cells",
    topicId: 'bio_ch8_t1',
    questionText: "Which of the following is not a characteristic of prokaryotic cells?",
    options: ["Mesosome", "Circular DNA", "Photosynthetic lamellae", "Membrane bound organelles"],
    correctAnswer: "Membrane bound organelles",
    explanation: "Prokaryotic cells lack membrane-bound organelles like mitochondria, Golgi apparatus, etc.",
    ncertReference: "NCERT Class 11 Biology, Chapter 8",
    year: 2021,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 8,
    subject: "Biology",
    chapter: "Biomolecules",
    topic: "Enzymes",
    topicId: 'bio_ch9_t1',
    questionText: "A non-proteinaceous enzyme is:",
    options: ["Lysozyme", "Ribozyme", "Ligase", "Deoxyribonuclease"],
    correctAnswer: "Ribozyme",
    explanation: "Ribozymes are RNA molecules that have catalytic activity.",
    ncertReference: "NCERT Class 11 Biology, Chapter 9",
    year: 2016,
    difficulty: "Medium",
    tags: ["PYQ"],
    type: "mcq",
  ),
  Question(
    id: 9,
    subject: "Biology",
    chapter: "Cell Cycle and Cell Division",
    topic: "Meiosis",
    topicId: 'bio_ch10_t1',
    questionText: "Crossing over takes place during which stage of meiosis?",
    options: ["Pachytene", "Zygotene", "Leptotene", "Diplotene"],
    correctAnswer: "Pachytene",
    explanation: "Crossing over occurs between non-sister chromatids of homologous chromosomes during the pachytene stage of Prophase I.",
    ncertReference: "NCERT Class 11 Biology, Chapter 10",
    year: 2020,
    difficulty: "Medium",
    tags: ["PYQ", "NCERT"],
    type: "mcq",
  ),
  Question(
    id: 10,
    subject: "Biology",
    chapter: "Photosynthesis in Higher Plants",
    topic: "Light Reaction",
    topicId: 'bio_ch13_t1',
    questionText: "The primary electron acceptor in PS II is:",
    options: ["Pheophytin", "Plastoquinone", "Cytochrome", "ATP"],
    correctAnswer: "Pheophytin",
    explanation: "In Photosystem II, the excited P680 transfers an electron to pheophytin.",
    ncertReference: "NCERT Class 11 Biology, Chapter 13",
    year: 2018,
    difficulty: "Hard",
    tags: ["PYQ"],
    type: "mcq",
  ),
  Question(
    id: 11,
    subject: "Biology",
    chapter: "Respiration in Plants",
    topic: "Glycolysis",
    topicId: 'bio_ch14_t1',
    questionText: "The end product of glycolysis is:",
    options: ["Pyruvic acid", "Acetyl CoA", "Citric acid", "Lactic acid"],
    correctAnswer: "Pyruvic acid",
    explanation: "Glycolysis breaks down one molecule of glucose into two molecules of pyruvic acid.",
    ncertReference: "NCERT Class 11 Biology, Chapter 14",
    year: 2019,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 12,
    subject: "Biology",
    chapter: "Human Reproduction",
    topic: "Menstrual Cycle",
    topicId: 'bio_ch3_12_t1',
    questionText: "The surge of which hormone triggers ovulation?",
    options: ["LH", "FSH", "Estrogen", "Progesterone"],
    correctAnswer: "LH",
    explanation: "A rapid surge of Luteinizing Hormone (LH) induces the rupture of Graafian follicle and release of ovum.",
    ncertReference: "NCERT Class 12 Biology, Chapter 3",
    year: 2020,
    difficulty: "Medium",
    tags: ["PYQ", "NCERT"],
    type: "mcq",
  ),
  Question(
    id: 13,
    subject: "Biology",
    chapter: "Principles of Inheritance and Variation",
    topic: "Mendelian Inheritance",
    topicId: 'bio_ch5_12_t1',
    questionText: "The phenotypic ratio of a dihybrid cross in F2 generation is:",
    options: ["9:3:3:1", "3:1", "1:2:1", "1:1:1:1"],
    correctAnswer: "9:3:3:1",
    explanation: "Mendel's dihybrid cross resulted in a 9:3:3:1 ratio of phenotypes in the F2 generation.",
    ncertReference: "NCERT Class 12 Biology, Chapter 5",
    year: 2021,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 14,
    subject: "Biology",
    chapter: "Molecular Basis of Inheritance",
    topic: "DNA Structure",
    topicId: 'bio_ch6_12_t1',
    questionText: "The pitch of DNA double helix is:",
    options: ["3.4 nm", "0.34 nm", "2 nm", "34 nm"],
    correctAnswer: "3.4 nm",
    explanation: "The pitch of the B-DNA helix is 3.4 nm, with about 10 base pairs per turn.",
    ncertReference: "NCERT Class 12 Biology, Chapter 6",
    year: 2022,
    difficulty: "Medium",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 15,
    subject: "Biology",
    chapter: "Evolution",
    topic: "Homologous Structures",
    topicId: 'bio_ch7_12_t1',
    questionText: "Thorns of Bougainvillea and tendrils of Cucurbita are examples of:",
    options: ["Homologous organs", "Analogous organs", "Vestigial organs", "Atavism"],
    correctAnswer: "Homologous organs",
    explanation: "They both represent axillary bud modifications, hence are homologous despite performing different functions.",
    ncertReference: "NCERT Class 12 Biology, Chapter 7",
    year: 2017,
    difficulty: "Medium",
    tags: ["PYQ", "NCERT"],
    type: "mcq",
  ),
  Question(
    id: 16,
    subject: "Biology",
    chapter: "Human Health and Disease",
    topic: "Immunity",
    topicId: 'bio_ch8_12_t1',
    questionText: "Which of the following is a primary lymphoid organ?",
    options: ["Bone marrow", "Spleen", "Peyer's patches", "Lymph nodes"],
    correctAnswer: "Bone marrow",
    explanation: "Bone marrow and thymus are primary lymphoid organs where lymphocytes mature.",
    ncertReference: "NCERT Class 12 Biology, Chapter 8",
    year: 2023,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 17,
    subject: "Biology",
    chapter: "Biotechnology: Principles and Processes",
    topic: "Restriction Enzymes",
    topicId: 'bio_ch11_12_t1',
    questionText: "The 'molecular scissors' used in genetic engineering are:",
    options: ["Restriction endonucleases", "Ligases", "Polymerases", "Helicases"],
    correctAnswer: "Restriction endonucleases",
    explanation: "Restriction enzymes cut DNA at specific palindromic sequences.",
    ncertReference: "NCERT Class 12 Biology, Chapter 11",
    year: 2019,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 18,
    subject: "Biology",
    chapter: "Organisms and Populations",
    topic: "Population Growth",
    topicId: 'bio_ch13_12_t1',
    questionText: "Which curve represents exponential growth?",
    options: ["J-shaped", "S-shaped", "Linear", "Bell-shaped"],
    correctAnswer: "J-shaped",
    explanation: "Exponential growth occurs when resources are unlimited, resulting in a J-shaped curve.",
    ncertReference: "NCERT Class 12 Biology, Chapter 13",
    year: 2020,
    difficulty: "Medium",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 19,
    subject: "Biology",
    chapter: "Ecosystem",
    topic: "Energy Flow",
    topicId: 'bio_ch14_12_t1',
    questionText: "The 10% law of energy transfer was proposed by:",
    options: ["Lindeman", "Odum", "Tansley", "Reiter"],
    correctAnswer: "Lindeman",
    explanation: "Raymond Lindeman proposed the 10% law, stating only 10% energy is transferred to the next trophic level.",
    ncertReference: "NCERT Class 12 Biology, Chapter 14",
    year: 2021,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 20,
    subject: "Biology",
    chapter: "Biodiversity and Conservation",
    topic: "In-situ Conservation",
    topicId: 'bio_ch15_12_t1',
    questionText: "Which of the following is not an in-situ conservation method?",
    options: ["Botanical gardens", "National parks", "Biosphere reserves", "Sacred groves"],
    correctAnswer: "Botanical gardens",
    explanation: "Botanical gardens are ex-situ conservation methods where plants are grown outside their natural habitat.",
    ncertReference: "NCERT Class 12 Biology, Chapter 15",
    year: 2022,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
  Question(
    id: 21,
    subject: "Biology",
    chapter: "The Living World",
    topic: "Taxonomy",
    topicId: 'bio_ch1_t2',
    type: 'AR',
    questionText: "Assertion (A): Hierarchical system of classification is useful. \nReason (R): It helps in easy identification and study of organisms.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A).",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A).",
      "(A) is true but (R) is false.",
      "(A) is false but (R) is true."
    ],
    correctAnswer: "Both (A) and (R) are true and (R) is the correct explanation of (A).",
    explanation: "Hierarchical classification organizes organisms into nested groups, which simplifies study and identification.",
    ncertReference: "NCERT Class 11, Chapter 1",
    difficulty: "Medium",
    tags: ["NCERT", "AR"],
  ),
  Question(
    id: 22,
    subject: "Biology",
    chapter: "Biological Classification",
    topic: "Kingdom Monera",
    topicId: 'bio_ch2_t1',
    type: 'Statement',
    questionText: "Statement I: Bacteria are the sole members of Kingdom Monera. \nStatement II: Bacteria exhibit the most extensive metabolic diversity.",
    options: [
      "Both Statement I and Statement II are correct.",
      "Both Statement I and Statement II are incorrect.",
      "Statement I is correct but Statement II is incorrect.",
      "Statement I is incorrect but Statement II is correct."
    ],
    correctAnswer: "Both Statement I and Statement II are correct.",
    explanation: "Kingdom Monera consists entirely of bacteria, and as a group, they show a wide range of metabolic activities.",
    ncertReference: "NCERT Class 11, Chapter 2",
    difficulty: "Medium",
    tags: ["NCERT", "Statement"],
  ),
];

// ============= CHEMISTRY QUESTIONS =============
final List<Question> chemistryQuestions = [
  Question(
    id: 101,
    subject: "Chemistry",
    chapter: "Some Basic Concepts of Chemistry",
    topic: "Mole Concept & Calculations",
    topicId: 'chem_ch1_t1',
    questionText: "The number of atoms in 0.1 mole of a triatomic gas is?",
    options: ["6.022×10²²", "1.806×10²³", "3.6×10²³", "1.8×10²²"],
    correctAnswer: "1.806×10²³",
    explanation: "1 mole of any substance contains Avogadro's number (6.022×10²³) of particles. For a triatomic molecule with 0.1 mole: 0.1 × 3 × 6.022×10²³ = 1.806×10²³ atoms.",
    ncertReference: "NCERT Class 11, Chapter 1, Page 12",
    year: 2024,
    difficulty: "Medium",
    tags: ["NCERT", "PYQ-2024", "Calculation"],
    type: "mcq",
  ),
  Question(
    id: 102,
    subject: "Chemistry",
    chapter: "Structure of Atom",
    topic: "Quantum Numbers",
    topicId: 'chem_ch2_t1',
    questionText: "The total number of orbitals associated with third shell is:",
    options: ["9", "4", "16", "3"],
    correctAnswer: "9",
    explanation: "Number of orbitals = n². For n=3, number of orbitals = 3² = 9 (one 3s, three 3p, five 3d).",
    ncertReference: "NCERT Class 11 Chemistry, Chapter 2",
    year: 2021,
    difficulty: "Medium",
    tags: ["NCERT"],
    type: "mcq",
  ),
];

// ============= PHYSICS QUESTIONS =============
final List<Question> physicsQuestions = [
  Question(
    id: 201,
    subject: "Physics",
    chapter: "Units and Measurements",
    topic: "Dimensions",
    topicId: 'phys_ch2_t1',
    questionText: "The dimensional formula for gravitational constant G is:",
    options: ["[M⁻¹L³T⁻²]", "[ML³T⁻²]", "[M⁻¹L²T⁻²]", "[ML²T⁻²]"],
    correctAnswer: "[M⁻¹L³T⁻²]",
    explanation: "F = G m1m2 / r² => G = F r² / m1m2. Units: [MLT⁻²][L²] / [M²] = [M⁻¹L³T⁻²].",
    ncertReference: "NCERT Class 11 Physics, Chapter 2",
    year: 2023,
    difficulty: "Medium",
    tags: ["NCERT", "PYQ"],
    type: "mcq",
  ),
  Question(
    id: 202,
    subject: "Physics",
    chapter: "Motion in a Straight Line",
    topic: "Kinematics",
    topicId: 'phys_ch3_t1',
    questionText: "For a body falling freely under gravity, distance covered in time t is proportional to:",
    options: ["t²", "t", "√t", "t³"],
    correctAnswer: "t²",
    explanation: "s = ut + ½gt². For free fall u=0, so s = ½gt² => s ∝ t².",
    ncertReference: "NCERT Class 11 Physics, Chapter 3",
    year: 2022,
    difficulty: "Easy",
    tags: ["NCERT"],
    type: "mcq",
  ),
];

// ============= SUBJECT STRUCTURE =============
final List<Subject> subjects = [
  Subject(
    id: 'bio',
    name: 'Biology',
    icon: '🧬',
    description: 'The study of living organisms and their interactions',
    chapters: [
      Chapter(
        id: 'bio_ch1',
        name: 'The Living World',
        subjectId: 'bio',
        description: 'Introduction to living organisms and taxonomy',
        classLevel: 'Class 11',
        weight: 1,
        topics: [
          Topic(
            id: 'bio_ch1_t1', 
            name: 'Characteristics of Living Organisms', 
            chapterId: 'bio_ch1', 
            questionCount: 4, 
            difficulty: 'Easy',
            summary: 'The living world is rich in variety. Millions of plants and animals have been identified and described but a large number still remains unknown. Life is a unique, complex organization of molecules, expressing through chemical reactions which lead to growth, development, responsiveness, adaptation and reproduction.',
            keyPoints: [
              'Growth: Increase in mass and increase in number of individuals are twin characteristics of growth.',
              'Reproduction: In living organisms, reproduction is the production of progeny possessing features more or less similar to those of parents.',
              'Metabolism: The sum total of all the chemical reactions occurring in our body is metabolism.',
              'Consciousness: All organisms, from the prokaryotes to the most complex eukaryotes can sense and respond to environmental cues.',
            ],
          ),
          Topic(
            id: 'bio_ch1_t2', 
            name: 'Diversity in Living Organisms', 
            chapterId: 'bio_ch1', 
            questionCount: 4, 
            difficulty: 'Medium',
            summary: 'The number of species that are known and described range between 1.7-1.8 million. This refers to biodiversity or the number and types of organisms present on earth. Taxonomy is the study of principles and procedures of classification.',
            keyPoints: [
              'Binomial Nomenclature: Each name has two components – the Generic name and the specific epithet.',
              'Taxonomic Categories: Kingdom, Phylum/Division, Class, Order, Family, Genus and Species.',
              'Species: It is a group of individual organisms with fundamental similarities.',
              'Herbarium: Store house of collected plant specimens that are dried, pressed and preserved on sheets.',
            ],
          ),
        ],
      ),
      Chapter(
        id: 'bio_ch2',
        name: 'Biological Classification',
        subjectId: 'bio',
        description: 'Five kingdom classification system',
        classLevel: 'Class 11',
        weight: 2,
        topics: [
          Topic(
            id: 'bio_ch2_t1',
            name: 'Monera & Protista',
            chapterId: 'bio_ch2',
            questionCount: 4,
            difficulty: 'Medium',
          ),
        ],
      ),
      Chapter(
        id: 'bio_ch3',
        name: 'Plant Kingdom',
        subjectId: 'bio',
        description: 'Classification of plants into algae, bryophytes, pteridophytes and gymnosperms',
        classLevel: 'Class 11',
        weight: 2,
        topics: [
          Topic(
            id: 'bio_ch3_t1',
            name: 'Algae',
            chapterId: 'bio_ch3',
            questionCount: 3,
            difficulty: 'Medium',
          ),
        ],
      ),
      Chapter(
        id: 'bio_ch4',
        name: 'Animal Kingdom',
        subjectId: 'bio',
        description: 'Classification and features of non-chordate and chordate phyla',
        classLevel: 'Class 11',
        weight: 2,
        topics: [
          Topic(
            id: 'bio_ch4_t1',
            name: 'Non-Chordate Phyla',
            chapterId: 'bio_ch4',
            questionCount: 3,
            difficulty: 'Medium',
          ),
        ],
      ),
      Chapter(
        id: 'bio_ch8',
        name: 'Cell: The Unit of Life',
        subjectId: 'bio',
        description: 'Structure of prokaryotic and eukaryotic cells',
        classLevel: 'Class 11',
        weight: 3,
        topics: [
          Topic(
            id: 'bio_ch8_t1',
            name: 'Cell Organelles',
            chapterId: 'bio_ch8',
            questionCount: 3,
            difficulty: 'Medium',
          ),
        ],
      ),
      Chapter(
        id: 'bio_ch9',
        name: 'Biomolecules',
        subjectId: 'bio',
        description: 'Chemical constituents and enzymes of living cells',
        classLevel: 'Class 11',
        weight: 2,
        topics: [
          Topic(
            id: 'bio_ch9_t1',
            name: 'Enzymes & Macromolecules',
            chapterId: 'bio_ch9',
            questionCount: 3,
            difficulty: 'Medium',
          ),
        ],
      ),
      Chapter(
        id: 'bio_ch10',
        name: 'Cell Cycle and Cell Division',
        subjectId: 'bio',
        description: 'Phases of cell cycle, mitosis and meiosis',
        classLevel: 'Class 11',
        weight: 2,
        topics: [
          Topic(
            id: 'bio_ch10_t1',
            name: 'Cell Cycle & Meiosis',
            chapterId: 'bio_ch10',
            questionCount: 3,
            difficulty: 'Medium',
          ),
        ],
      ),
      Chapter(
        id: 'bio_ch13',
        name: 'Photosynthesis in Higher Plants',
        subjectId: 'bio',
        description: 'Light reaction, Calvin cycle and C4 pathway',
        classLevel: 'Class 11',
        weight: 3,
        topics: [
          Topic(
            id: 'bio_ch13_t1',
            name: 'Light Reaction & Calvin Cycle',
            chapterId: 'bio_ch13',
            questionCount: 3,
            difficulty: 'Hard',
          ),
        ],
      ),
      Chapter(
        id: 'bio_ch14',
        name: 'Respiration in Plants',
        subjectId: 'bio',
        description: 'Glycolysis, Krebs cycle and electron transport chain',
        classLevel: 'Class 11',
        weight: 2,
        topics: [
          Topic(
            id: 'bio_ch14_t1',
            name: 'Glycolysis, Krebs Cycle & ETC',
            chapterId: 'bio_ch14',
            questionCount: 3,
            difficulty: 'Medium',
          ),
        ],
      ),
      Chapter(
        id: 'bio_ch3_12',
        name: 'Human Reproduction',
        subjectId: 'bio',
        description: 'Reproductive system, gametogenesis and menstrual cycle',
        classLevel: 'Class 12',
        weight: 3,
        topics: [
          Topic(
            id: 'bio_ch3_12_t1',
            name: 'Gametogenesis & Menstrual Cycle',
            chapterId: 'bio_ch3_12',
            questionCount: 3,
            difficulty: 'Medium',
          ),
        ],
      ),
      Chapter(
        id: 'bio_ch5_12',
        name: 'Principles of Inheritance and Variation',
        subjectId: 'bio',
        description: 'Mendelian genetics and deviations from it',
        classLevel: 'Class 12',
        weight: 3,
        topics: [
          Topic(
            id: 'bio_ch5_12_t1',
            name: 'Mendelian Inheritance',
            chapterId: 'bio_ch5_12',
            questionCount: 3,
            difficulty: 'Medium',
          ),
        ],
      ),
      Chapter(
        id: 'bio_ch6_12',
        name: 'Molecular Basis of Inheritance',
        subjectId: 'bio',
        description: 'DNA structure, replication and genetic code',
        classLevel: 'Class 12',
        weight: 3,
        topics: [
          Topic(
            id: 'bio_ch6_12_t1',
            name: 'DNA Replication & Genetic Code',
            chapterId: 'bio_ch6_12',
            questionCount: 3,
            difficulty: 'Hard',
          ),
        ],
      ),
      Chapter(
        id: 'bio_ch7_12',
        name: 'Evolution',
        subjectId: 'bio',
        description: 'Origin of life, evidence and mechanism of evolution',
        classLevel: 'Class 12',
        weight: 2,
        topics: [
          Topic(
            id: 'bio_ch7_12_t1',
            name: 'Origin of Life & Homology',
            chapterId: 'bio_ch7_12',
            questionCount: 3,
            difficulty: 'Medium',
          ),
        ],
      ),
      Chapter(
        id: 'bio_ch8_12',
        name: 'Human Health and Disease',
        subjectId: 'bio',
        description: 'Immunity, diseases and their prevention',
        classLevel: 'Class 12',
        weight: 2,
        topics: [
          Topic(
            id: 'bio_ch8_12_t1',
            name: 'Immunity & Common Diseases',
            chapterId: 'bio_ch8_12',
            questionCount: 3,
            difficulty: 'Medium',
          ),
        ],
      ),
      Chapter(
        id: 'bio_ch11_12',
        name: 'Biotechnology: Principles and Processes',
        subjectId: 'bio',
        description: 'Tools of recombinant DNA technology',
        classLevel: 'Class 12',
        weight: 2,
        topics: [
          Topic(
            id: 'bio_ch11_12_t1',
            name: 'Tools of Recombinant DNA',
            chapterId: 'bio_ch11_12',
            questionCount: 3,
            difficulty: 'Medium',
          ),
        ],
      ),
      Chapter(
        id: 'bio_ch13_12',
        name: 'Organisms and Populations',
        subjectId: 'bio',
        description: 'Population attributes and interspecific interactions',
        classLevel: 'Class 12',
        weight: 1,
        topics: [
          Topic(
            id: 'bio_ch13_12_t1',
            name: 'Population Interactions',
            chapterId: 'bio_ch13_12',
            questionCount: 2,
            difficulty: 'Medium',
          ),
        ],
      ),
      Chapter(
        id: 'bio_ch14_12',
        name: 'Ecosystem',
        subjectId: 'bio',
        description: 'Structure and function of ecosystems, energy flow',
        classLevel: 'Class 12',
        weight: 1,
        topics: [
          Topic(
            id: 'bio_ch14_12_t1',
            name: 'Energy Flow',
            chapterId: 'bio_ch14_12',
            questionCount: 2,
            difficulty: 'Medium',
          ),
        ],
      ),
      Chapter(
        id: 'bio_ch15_12',
        name: 'Biodiversity and Conservation',
        subjectId: 'bio',
        description: 'Patterns of biodiversity and conservation strategies',
        classLevel: 'Class 12',
        weight: 1,
        topics: [
          Topic(
            id: 'bio_ch15_12_t1',
            name: 'Biodiversity',
            chapterId: 'bio_ch15_12',
            questionCount: 2,
            difficulty: 'Medium',
          ),
        ],
      ),
    ],
  ),
  Subject(
    id: 'chem',
    name: 'Chemistry',
    icon: '⚗️',
    description: 'The study of matter and its transformations',
    chapters: [
      Chapter(
        id: 'chem_ch1', 
        name: 'Basic Concepts', 
        subjectId: 'chem', 
        description: 'Mole concept and stoichiometry',
        classLevel: 'Class 11', 
        weight: 2, 
        topics: [
          Topic(
            id: 'chem_ch1_t1', 
            name: 'Mole Concept', 
            chapterId: 'chem_ch1', 
            questionCount: 5, 
            difficulty: 'Medium',
            summary: 'One mole is the amount of a substance that contains as many particles or entities as there are atoms in exactly 12 g of the 12C isotope. The mass of one mole of a substance in grams is called its molar mass.',
            keyPoints: [
              'Avogadro Number (NA): 6.022 × 10²³',
              'Molar Mass: Mass of 1 mole of substance in grams.',
              'Molar Volume: At STP, 1 mole of any gas occupies 22.4 litres.',
              'Empirical Formula: Simplest whole number ratio of various atoms present in a compound.',
            ],
          ),
        ],
      ),
      Chapter(
        id: 'chem_ch2',
        name: 'Structure of Atom',
        subjectId: 'chem',
        description: 'Sub-atomic particles and quantum numbers',
        classLevel: 'Class 11',
        weight: 2,
        topics: [
          Topic(
            id: 'chem_ch2_t1',
            name: 'Quantum Numbers',
            chapterId: 'chem_ch2',
            questionCount: 5,
            difficulty: 'Medium',
          ),
        ],
      ),
    ],
  ),
  Subject(
    id: 'phys',
    name: 'Physics',
    icon: '⚛️',
    description: 'The study of nature and its laws',
    chapters: [
      Chapter(
        id: 'phys_ch2', 
        name: 'Units & Measurements', 
        subjectId: 'phys', 
        description: 'SI units, dimensions and significant figures',
        classLevel: 'Class 11', 
        weight: 1, 
        topics: [
          Topic(
            id: 'phys_ch2_t1', 
            name: 'Dimensions', 
            chapterId: 'phys_ch2', 
            questionCount: 5, 
            difficulty: 'Medium',
            summary: 'The dimensions of a physical quantity are the powers to which the base quantities are raised to represent that quantity. Dimensional analysis is a tool to check the consistency of equations and to derive relations between physical quantities.',
            keyPoints: [
              'Base Quantities: Length [L], Mass [M], Time [T], etc.',
              'Principle of Homogeneity: Dimensions of all terms in a physical equation must be the same.',
              'Applications: Checking correctness of equations, converting units, deriving relations.',
              'Limitations: Cannot determine dimensionless constants.',
            ],
          ),
        ],
      ),
      Chapter(
        id: 'phys_ch3',
        name: 'Motion in a Straight Line',
        subjectId: 'phys',
        description: 'Kinematics of a particle in one dimension',
        classLevel: 'Class 11',
        weight: 2,
        topics: [
          Topic(
            id: 'phys_ch3_t1',
            name: 'Kinematics',
            chapterId: 'phys_ch3',
            questionCount: 5,
            difficulty: 'Medium',
          ),
        ],
      ),
    ],
  ),
];

// Helper function to get all questions as flat list for database
List<Question> getAllQuestions() {
  return [...biologyQuestions, ...chemistryQuestions, ...physicsQuestions];
}

// Helper function to get questions for a specific topic
List<Question> getQuestionsForTopic(String topicId) {
  final allQuestions = getAllQuestions();
  return allQuestions.where((q) => q.topicId == topicId).toList();
}
