import 'package:drift/drift.dart' show Value;
import '../database/drift_database.dart' show FlashcardsCompanion;

/// High-yield NCERT-grounded flashcards seeded on first install.
/// Covers Biology, Chemistry, and Physics — Class 11 & 12 core facts.
List<FlashcardsCompanion> getStarterFlashcards() {
  return [
    // ── Biology (Class 11) ──
    _fc(
      'bio_11_01',
      'What is the powerhouse of the cell?',
      'Mitochondria — site of aerobic respiration and ATP synthesis.',
      'Biology',
      'Cell: The Unit of Life',
      ncertRef: 'NCERT Class 11 Biology, Ch 8',
      difficulty: 'Easy',
    ),
    _fc(
      'bio_11_02',
      'Who proposed the cell theory?',
      'Matthias Schleiden and Theodor Schwann (1838–39). Rudolf Virchow added "Omnis cellula e cellula".',
      'Biology',
      'Cell: The Unit of Life',
      ncertRef: 'NCERT Class 11 Biology, Ch 8',
      difficulty: 'Easy',
    ),
    _fc(
      'bio_11_03',
      'What is the fluid mosaic model of plasma membrane?',
      'Proposed by Singer and Nicolson (1972). Lipids and proteins float freely in a bilayer — "mosaic" of proteins on a fluid lipid sea.',
      'Biology',
      'Biomolecules',
      ncertRef: 'NCERT Class 11 Biology, Ch 9',
      difficulty: 'Medium',
    ),
    _fc(
      'bio_11_04',
      'Enzyme specificity is explained by...',
      'Lock-and-key model (Fischer) and Induced-fit model (Koshland). Active site fits substrate like a glove.',
      'Biology',
      'Enzymes',
      ncertRef: 'NCERT Class 11 Biology, Ch 6',
      difficulty: 'Medium',
    ),
    _fc(
      'bio_11_05',
      'What is the primary alcohol in photosynthesis?',
      'Glyceraldehyde-3-phosphate (G3P) — the first stable product of the Calvin cycle.',
      'Biology',
      'Photosynthesis',
      ncertRef: 'NCERT Class 11 Biology, Ch 13',
      difficulty: 'Medium',
    ),
    _fc(
      'bio_11_06',
      'C4 plants have Kranz anatomy. Which enzyme fixes CO₂ first?',
      'PEP carboxylase in mesophyll cells fixes CO₂ into oxaloacetate (4C). Rubisco acts in bundle-sheath cells.',
      'Biology',
      'Photosynthesis',
      ncertRef: 'NCERT Class 11 Biology, Ch 13',
      difficulty: 'Hard',
    ),
    _fc(
      'bio_11_07',
      'What is the endosymbiotic theory?',
      'Mitochondria and chloroplasts evolved from free-living prokaryotes engulfed by ancestral eukaryotic cells. Evidence: own DNA, 70S ribosomes, double membrane.',
      'Biology',
      'Cell: The Unit of Life',
      ncertRef: 'NCERT Class 11 Biology, Ch 8',
      difficulty: 'Medium',
    ),
    _fc(
      'bio_11_08',
      'Law of Dominance was proposed by...',
      'Gregor Johann Mendel. Dominant allele masks recessive in F₁ heterozygote.',
      'Biology',
      'Principles of Inheritance',
      ncertRef: 'NCERT Class 11 Biology, Ch 5',
      difficulty: 'Easy',
    ),
    _fc(
      'bio_11_09',
      'What is the rough ER studded with?',
      'Ribosomes — site of protein synthesis and translocation into ER lumen.',
      'Biology',
      'Cell: The Unit of Life',
      ncertRef: 'NCERT Class 11 Biology, Ch 8',
      difficulty: 'Easy',
    ),
    _fc(
      'bio_11_10',
      'What is the chemiosmotic hypothesis?',
      'Peter Mitchell (1961). ATP synthesis driven by proton gradient across inner mitochondrial membrane via ATP synthase (F₀-F₁ complex).',
      'Biology',
      'Respiration in Plants',
      ncertRef: 'NCERT Class 11 Biology, Ch 14',
      difficulty: 'Hard',
    ),

    // ── Biology (Class 12) ──
    _fc(
      'bio_12_01',
      'What is the lac operon?',
      'Inducible operon in E. coli. Lactose (inducer) binds repressor → RNA pol transcribes lacZ, lacY, lacA. Negative regulation + positive control by CAP-cAMP.',
      'Biology',
      'Molecular Basis of Inheritance',
      ncertRef: 'NCERT Class 12 Biology, Ch 6',
      difficulty: 'Medium',
    ),
    _fc(
      'bio_12_02',
      'Central Dogma of Molecular Biology:',
      'DNA → (transcription) → RNA → (translation) → Protein. Reverse transcription (RNA → DNA) by retroviruses is an exception.',
      'Biology',
      'Molecular Basis of Inheritance',
      ncertRef: 'NCERT Class 12 Biology, Ch 5',
      difficulty: 'Easy',
    ),
    _fc(
      'bio_12_03',
      'What is satellite DNA used for in forensics?',
      'Variable number tandem repeats (VNTRs) are unique to individuals. DNA fingerprinting uses probe hybridization to these repeats.',
      'Biology',
      'Molecular Basis of Inheritance',
      ncertRef: 'NCERT Class 12 Biology, Ch 5',
      difficulty: 'Medium',
    ),
    _fc(
      'bio_12_04',
      'Antibody structure: how many polypeptide chains?',
      '4 chains — 2 heavy (H) and 2 light (L), linked by disulfide bonds. Variable region at N-terminus, constant region at C-terminus.',
      'Biology',
      'Human Health and Disease',
      ncertRef: 'NCERT Class 12 Biology, Ch 8',
      difficulty: 'Medium',
    ),
    _fc(
      'bio_12_05',
      'What is the difference between innate and adaptive immunity?',
      'Innate: non-specific, present from birth (skin, phagocytes, inflammation). Adaptive: specific, has memory (B and T lymphocytes).',
      'Biology',
      'Human Health and Disease',
      ncertRef: 'NCERT Class 12 Biology, Ch 8',
      difficulty: 'Easy',
    ),
    _fc(
      'bio_12_06',
      'Hardy-Weinberg equilibrium requires...',
      'No mutation, no gene flow, random mating, infinite population size, no natural selection. Allele frequencies remain constant across generations.',
      'Biology',
      'Evolution',
      ncertRef: 'NCERT Class 12 Biology, Ch 7',
      difficulty: 'Medium',
    ),
    _fc(
      'bio_12_07',
      'What is the ecological pyramid of energy?',
      'Always upright — energy decreases at each trophic level. Only ~10% transfers between levels (10% law).',
      'Biology',
      'Ecosystem',
      ncertRef: 'NCERT Class 12 Biology, Ch 13',
      difficulty: 'Easy',
    ),

    // ── Chemistry (Class 11) ──
    _fc(
      'chem_11_01',
      'What is hybridisation of carbon in ethene (C₂H₄)?',
      'sp² hybridisation — trigonal planar, bond angle 120°, one π bond + three σ bonds.',
      'Chemistry',
      'Chemical Bonding',
      ncertRef: 'NCERT Class 11 Chemistry, Ch 4',
      difficulty: 'Easy',
    ),
    _fc(
      'chem_11_02',
      'Hess\'s Law states...',
      'Total enthalpy change is independent of the path taken. ΔH depends only on initial and final states. Used to calculate ΔH_f indirectly.',
      'Chemistry',
      'Thermodynamics',
      ncertRef: 'NCERT Class 11 Chemistry, Ch 6',
      difficulty: 'Medium',
    ),
    _fc(
      'chem_11_03',
      'What is the IUPAC name of CH₃CH(OH)CH₂CH₃?',
      'Butan-2-ol (2-butanol). Functional group: –OH at C2. Longest chain: 4 carbons.',
      'Chemistry',
      'Organic Chemistry Basics',
      ncertRef: 'NCERT Class 11 Chemistry, Ch 12',
      difficulty: 'Easy',
    ),
    _fc(
      'chem_11_04',
      'Raoult\'s Law:',
      'P_solution = χ_solvent × P°_solvent. Partial vapour pressure of each component is proportional to its mole fraction in solution.',
      'Chemistry',
      'Solutions',
      ncertRef: 'NCERT Class 11 Chemistry, Ch 2',
      difficulty: 'Medium',
    ),
    _fc(
      'chem_11_05',
      'What is the SI unit of molar conductivity?',
      'S cm² mol⁻¹ (or equivalently, m² S mol⁻¹). Λ_m = κ / c where κ = conductivity, c = concentration.',
      'Chemistry',
      'Electrochemistry',
      ncertRef: 'NCERT Class 11 Chemistry, Ch 3',
      difficulty: 'Medium',
    ),
    _fc(
      'chem_11_06',
      'Markovnikov\'s rule:',
      'In addition of HX to asymmetrical alkene, H attaches to carbon with more H atoms; X attaches to carbon with fewer H atoms (more substituted carbocation).',
      'Chemistry',
      'Hydrocarbons',
      ncertRef: 'NCERT Class 11 Chemistry, Ch 13',
      difficulty: 'Medium',
    ),

    // ── Chemistry (Class 12) ──
    _fc(
      'chem_12_01',
      'What is a co-ordinate (dative) bond?',
      'A bond where both electrons in the shared pair come from one atom. Example: NH₄⁺ — N donates lone pair to H⁺.',
      'Chemistry',
      'Coordination Compounds',
      ncertRef: 'NCERT Class 12 Chemistry, Ch 9',
      difficulty: 'Easy',
    ),
    _fc(
      'chem_12_02',
      'What is the coordination number in [Co(NH₃)₆]³⁺?',
      '6 — six NH₃ ligands bonded to Co³⁺. Octahedral geometry.',
      'Chemistry',
      'Coordination Compounds',
      ncertRef: 'NCERT Class 12 Chemistry, Ch 9',
      difficulty: 'Easy',
    ),
    _fc(
      'chem_12_03',
      'E₁ and E₂ elimination — key difference?',
      'E₁: two-step, unimolecular (rate = k[substrate]), carbocation intermediate, follows Zaitsev rule. E₂: one-step, bimolecular (rate = k[substrate][base]), anti-periplanar geometry required.',
      'Chemistry',
      'Haloalkanes and Haloarenes',
      ncertRef: 'NCERT Class 12 Chemistry, Ch 10',
      difficulty: 'Hard',
    ),
    _fc(
      'chem_12_04',
      'What is the Tollens\' reagent test?',
      'Ammoniacal silver nitrate [Ag(NH₃)₂]⁺. Aldehydes reduce it → silver mirror (Ag). Ketones (except α-hydroxy ketones) do not.',
      'Chemistry',
      'Aldehydes, Ketones',
      ncertRef: 'NCERT Class 12 Chemistry, Ch 12',
      difficulty: 'Easy',
    ),
    _fc(
      'chem_12_05',
      'What is Le Chatelier\'s Principle?',
      'If a system at equilibrium is disturbed, it shifts in the direction that partially counteracts the change. Used to predict effect of T, P, concentration changes.',
      'Chemistry',
      'Equilibrium',
      ncertRef: 'NCERT Class 12 Chemistry, Ch 7',
      difficulty: 'Easy',
    ),
    _fc(
      'chem_12_06',
      'What are Lanthanoid contraction?',
      'Steady decrease in atomic/ionic radii from La to Lu due to poor shielding by 4f electrons. Causes similar sizes of 2nd and 3rd transition series elements.',
      'Chemistry',
      'd- and f-Block Elements',
      ncertRef: 'NCERT Class 12 Chemistry, Ch 8',
      difficulty: 'Hard',
    ),

    // ── Physics (Class 11) ──
    _fc(
      'phys_11_01',
      'What is the dimensional formula of force?',
      '[MLT⁻²]. From F = ma: mass × acceleration = M × LT⁻².',
      'Physics',
      'Units and Measurements',
      ncertRef: 'NCERT Class 11 Physics, Ch 1',
      difficulty: 'Easy',
    ),
    _fc(
      'phys_11_02',
      'Newton\'s First Law is also called...',
      'Law of Inertia. A body remains at rest or in uniform motion unless acted upon by an external force.',
      'Physics',
      'Laws of Motion',
      ncertRef: 'NCERT Class 11 Physics, Ch 5',
      difficulty: 'Easy',
    ),
    _fc(
      'phys_11_03',
      'What is the work-energy theorem?',
      'Net work done on a body = change in its kinetic energy. W_net = ΔKE = ½mv² – ½mu².',
      'Physics',
      'Work, Energy and Power',
      ncertRef: 'NCERT Class 11 Physics, Ch 6',
      difficulty: 'Easy',
    ),
    _fc(
      'phys_11_04',
      'What is the centre of mass of a two-particle system?',
      'x_cm = (m₁x₁ + m₂x₂)/(m₁ + m₂). Position depends only on masses and their positions.',
      'Physics',
      'System of Particles',
      ncertRef: 'NCERT Class 11 Physics, Ch 7',
      difficulty: 'Easy',
    ),
    _fc(
      'phys_11_05',
      'What is simple harmonic motion (SHM)?',
      'Restoring force proportional to displacement: F = –kx. Position: x = A sin(ωt + φ). Time period T = 2π√(m/k).',
      'Physics',
      'Oscillations',
      ncertRef: 'NCERT Class 11 Physics, Ch 14',
      difficulty: 'Medium',
    ),
    _fc(
      'phys_11_06',
      'What is the Escape Velocity from Earth?',
      'v_esc = √(2gR) ≈ 11.2 km/s. Minimum velocity for a body to escape Earth\'s gravitational field.',
      'Physics',
      'Gravitation',
      ncertRef: 'NCERT Class 11 Physics, Ch 8',
      difficulty: 'Medium',
    ),
    _fc(
      'phys_11_07',
      'What is the first law of thermodynamics?',
      'ΔU = Q – W. Change in internal energy = heat added to system – work done by system. Equivalent to conservation of energy.',
      'Physics',
      'Thermal Properties of Matter',
      ncertRef: 'NCERT Class 11 Physics, Ch 11',
      difficulty: 'Medium',
    ),

    // ── Physics (Class 12) ──
    _fc(
      'phys_12_01',
      'What is Coulomb\'s Law?',
      'F = kq₁q₂/r². Force between two point charges is directly proportional to product of charges and inversely proportional to square of distance.',
      'Physics',
      'Electric Charges and Fields',
      ncertRef: 'NCERT Class 12 Physics, Ch 1',
      difficulty: 'Easy',
    ),
    _fc(
      'phys_12_02',
      'What is Gauss\'s Law for electric fields?',
      '∮E·dA = q_enc/ε₀. Total electric flux through a closed surface equals enclosed charge divided by permittivity.',
      'Physics',
      'Electric Charges and Fields',
      ncertRef: 'NCERT Class 12 Physics, Ch 1',
      difficulty: 'Medium',
    ),
    _fc(
      'phys_12_03',
      'What is the principle of a cyclotron?',
      'Charged particles accelerated by alternating electric field between two D-shaped chambers. Magnetic field makes them spiral outward. T = 2πm/qB (independent of velocity).',
      'Physics',
      'Magnetic Effects of Current',
      ncertRef: 'NCERT Class 12 Physics, Ch 4',
      difficulty: 'Medium',
    ),
    _fc(
      'phys_12_04',
      'Lenz\'s Law:',
      'Induced current flows in a direction that opposes the change in magnetic flux that produced it. Conservation of energy in electromagnetic induction.',
      'Physics',
      'Electromagnetic Induction',
      ncertRef: 'NCERT Class 12 Physics, Ch 6',
      difficulty: 'Easy',
    ),
    _fc(
      'phys_12_05',
      'What is the de Broglie wavelength?',
      'λ = h/p = h/mv. Every moving particle has a wave nature. Significant for subatomic particles (e.g., electrons in electron microscope).',
      'Physics',
      'Atoms',
      ncertRef: 'NCERT Class 12 Physics, Ch 12',
      difficulty: 'Medium',
    ),
    _fc(
      'phys_12_06',
      'What is the photoelectric equation?',
      'K_max = hν – φ₀. Maximum kinetic energy of ejected electron = energy of photon – work function. Proved by Einstein (Nobel 1921).',
      'Physics',
      'Dual Nature of Radiation',
      ncertRef: 'NCERT Class 12 Physics, Ch 11',
      difficulty: 'Medium',
    ),
    _fc(
      'phys_12_07',
      'What is nuclear binding energy?',
      'Energy required to disassemble nucleus into constituent protons and neutrons. Binding energy per nucleon peaks at Fe-56 (~8.8 MeV) — most stable nucleus.',
      'Physics',
      'Nuclei',
      ncertRef: 'NCERT Class 12 Physics, Ch 13',
      difficulty: 'Hard',
    ),
    _fc(
      'phys_12_08',
      'What is the logic gate for NAND?',
      'Output is LOW only when both inputs are HIGH. NAND is a universal gate — any logic circuit can be built using only NAND gates.',
      'Physics',
      'Semiconductor Electronics',
      ncertRef: 'NCERT Class 12 Physics, Ch 14',
      difficulty: 'Easy',
    ),
  ];
}

FlashcardsCompanion _fc(
  String id,
  String front,
  String back,
  String subject,
  String chapterId, {
  String ncertRef = '',
  String difficulty = 'Medium',
}) {
  return FlashcardsCompanion(
    id: Value(id),
    front: Value(front),
    back: Value(back),
    subject: Value(subject),
    topicId: Value(chapterId),
    chapterId: Value(chapterId),
    ncertReference: Value(ncertRef),
    difficulty: Value(difficulty),
    isGenerated: const Value(false),
    dueAt: Value(DateTime.now()),
  );
}
